### ISSUE TITLE
CPU pegged while "idle"

### ISSUE THREAD

**Issue by sl33nyc** [plietar/librespot#10]
When the `PlayerInternal` isn't playing, the CPU is pegged.  I believe [this line](https://github.com/plietar/librespot/blob/267ccbe65edfdd0a780ed445737f2cfc46308aa8/src/player.rs#L88) is the culprit.  Basically, when `PlayerInternal` is not playing audio, the `Receiver<PlayerCommand>` is being constantly polled.  Could `PlayerInternal` be refactored so `Receiver.recv()` is called and therefore blocks when there is no commands to change state?

(I tried doing this myself, but I'm really new to Rust and the type system with the "ownership" concept appears rather challenging to learn!  I would love to learn by example... :smile:)

**Comment by herrernst** [comment]
100% CPU also for me, not enough Rust skills to analyse this.

**Comment by plietar** [comment]
Fixed by 22d586e
