### ISSUE TITLE
Add support for executing commands when playback begins or ends

### ISSUE THREAD

**Issue by joerg-krause** [plietar/librespot#100]
Add an option to set commands, e.g. some shell script, which are executed if playback is about to begin or has stopped. This is quite handy to wakeup some amplifier from sleep or to stop any other service possibly blocking the audio interface.

**Comment by janderholm** [comment]
Perhaps it would be possible to implement the MPRIS dbus interface? I think it would be neat as many other clients use it and by subscribing to "org.freedesktop.DBus.Properties.PropertiesChanged" you can be notified whenever playback status is changed:

https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html

**Comment by joerg-krause** [comment]
@Fulkerson The MPRIS dbus intercase looks promising.However, I guess it takes more effort than adding the Rust feature `std::process::Command` in the `start()` and `stop()` functions of the audio backend.

@plietar What do you think?

**Comment by TonioRoffo** [comment]
I'd like scripts at the point a device connects or disconnects; it would allow projects like Volumio or squeezeplay to shut down and allow the soundcard to be shared between apps.  Does librespot free the soundcard when it disconnects from a player?

**Comment by herrernst** [comment]
> Does librespot free the soundcard when it disconnects from a player?

Yes, it does, even on pause/stop.

**Comment by plietar** [comment]
Fixed by #117
