### ISSUE TITLE
Use multimedia keys for remote control

### ISSUE THREAD

**Issue by joerg-krause** [plietar/librespot#101]
It would be great if the audio stream can be controlled with some multimedia keys like start, stop, prev, next.

**Comment by joerg-krause** [comment]
I have seen that the `SpircManager` implements functions like `send_pause()`. Is this the right place to start with? If so, how can those functions be accessed from an external process?

**Comment by plietar** [comment]
The way to go for this is to use separate program which sends commands to librespot over Spotify Connect.
You can use an official Spotify client, [spotcontrol](https://github.com/badfortrains/spotcontrol) (includes a chrome extension) or make a binary which links to librespot.

For the latter, you would call `send_pause()` and al on the `SpircManager`.

I'm happy to make librespot more modular if necessary for this, but the feature itself is out of scope.

cc @SimonPersson who I think was interested in something like that

**Comment by joerg-krause** [comment]
I see! I would prefer the latter way and link against librespot. I guess I can take https://github.com/plietar/spotsync as an example of howto use librespot, right?

**Comment by SimonTeixidor** [comment]
@plietar: I am indeed interested in this! There's just too little time for all the things I want to work on :)

I think some things could be changed to librespot in order for it to feel more natural as a library for just controlling other clients. For instance, it should be possible to create a `SpircManager` without a player. Overall, it's working quite well though!

**Comment by joerg-krause** [comment]
I am experimenting with sending commands using the SpircManager. I've had a look at https://github.com/Spotifyd/spotifyd-http, which is a good example of how to use librespot.

However, I've a question about the devices. I know that I can use `devices()` from the SpircManager to get all devices. In spotifyd-http the user manually selects a device from the list of devices.

My goal is to control the playback with keys, so which devices should be selected to send the command to? Just iterate over the list and send it to all? Or just the first entry in the list?

**Comment by joerg-krause** [comment]
@plietar @SimonPersson I am trying to get remote control to work by using the SpircManager. For this I enhanced librespot with a socket listener who's listening for commands like "next". If a command is received on the socket, the corresponding spirc command is called, e.g. `send_next()`.

Actually, the spotify player jumps to the next track, but also loses the connection to the librespot client. The next track is played locally by the spotify player, but not on the client. Any idea why?

**Comment by SimonTeixidor** [comment]
@joerg-krause I'm not sure I understand the question in your first comment. Do you run multiple librespot instances (or Spotify connect devices)? Otherwise, just fetch the device list:
```
curl 192.168.0.16:6767/devices
{"da6998c829f71f56896ed5944a9875ea9ab4b47f":"rpi"}
```
And grab the ID of the device you want to play on. Then send commands to that device.

As for your second question, are you sending the command to the right device then? I could see that happening if you do `send_next()` to the wrong device.

**Comment by joerg-krause** [comment]
@SimonPersson I have two clients and each one runs an instance of librespot. Furthermore, I have two Spotify players running, one on a PC, one on an iPhone.

Note, that I want to use the playing librespot client itself to emit the command, so I do not have two instances of librespot on the same device.

After playing with spotfiy-http I realized that I have to use the identifier of the librespot client itself and not of the Spotify player (on the PC).

So, I patched librespot so I can get the own identifier of the SpircManager and allowed the SpircManager to handle messages coming from itself (except Notify).

**Comment by joerg-krause** [comment]
@plietar @SimonPersson I managed to get the commands "playpause", "next" and "prev" to work. However, I wonder why there is no "stop"?

**Comment by sashahilton00** [comment]
Probably because you never stop music in the Spotify clients, just pause it?

**Comment by SimonTeixidor** [comment]
Great!

Is there a stop in the official client? What do you expect it to do?

**Comment by joerg-krause** [comment]
From an ALSA point of view I would say that a "stop" releases the audio output whereas a "pause" does not. Furthermore, I would expect that a "play" after a "pause" begins where the track was paused, whereas a "play" after a "stop" begins at the beginning of the track.

For now, I map "stop" to "pause".

**Comment by 1337sup3rh4x0r** [comment]
Hi @joerg-krause, I have been reading your posts here and I think I am trying to acchieve someting similar.
I would like to be able to send play/pause and next commands to the librespot player from my home automation system FHEM.
I see you added a socket listener and am thinking I could use this.
If I compile your branch, how would I then send the command to that socket?

**Comment by SimonTeixidor** [comment]
Does https://github.com/Spotifyd/spotifyd-http not do what you want? It
just seems like a http api would be easier then a custom protocol over
sockets to me.

On 20 Dec 2016 13:44, "1337sup3rh4x0r" <notifications@github.com> wrote:

Hi @joerg-krause <https://github.com/joerg-krause>, I have been reading
your posts here and I think I am trying to acchieve someting similar.
I would like to be able to send play/pause and next commands to the
librespot player from my home automation system FHEM.
I see you added a socket listener and am thinking I could use this.
If I compile your branch, how would I then send the command to that socket?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/plietar/librespot/issues/101#issuecomment-268234380>,
or mute the thread

**Comment by 1337sup3rh4x0r** [comment]
Maybe. There is just too little docu there for it to make any sense to me.
I am totally missing how I would even start with that one.

But if it is a deamon that receives http requests and forwards them to the librespot player in a language it understands, then I guess it is what I am looking for. :)

Edit: Ok, looking at an issue in your repo, it seems to be quite easy. Will give it a try later. Thanks for the tip!

**Comment by joerg-krause** [comment]
Hi @1337sup3rh4x0r I think you should try spotify-http as suggested by @SimonPersson.

I'm using the socket listener because I'm running a device with multimedia keys attached. This way, I can use some key event listener which emits the command to the socket - some kind of local remote control. The advantage in regard to spotify-httpd is that I only need a single instance of librespot running on my device.

**Comment by 1337sup3rh4x0r** [comment]
So does spotify-httpd start its own instance of librespot? I think then that is not what I am looking for. I was hoping it would be a tool to close the gap beween FHEM and librespot via http

**Comment by SimonTeixidor** [comment]
It uses the librespot library to communicate over the Spotify Connect
protocol, but does not do any playback, so it's not equivalent to an
instance of the librespot binary, which plays the music as well.

It seems to me like it could fill the gap like you want it to.

**Comment by 1337sup3rh4x0r** [comment]
Ok, I will give it a try tonight.
Thanks for the consulting!

**Comment by 1337sup3rh4x0r** [comment]
Thanks @SimonPersson , it's working great! Just what I was looking for.
Maybe if you find time, you can add these few lines to the readme on how to install and run your demon:

### Requirements:
On FreeBSD I had to install the following packages: rust, cargo, pkgconf, git

### Download and Build:
git clone https://github.com/Spotifyd/spotifyd-http.git
cd spotifyd-http/
cargo build
### Run:
target/debug/spotifyd-http --name Controller --username SPOTIFYUSERNAME --password SPOTIFYPASSWORD
