### ISSUE TITLE
Properly close connection

### ISSUE THREAD

**Issue by joerg-krause** [plietar/librespot#114]
When stopping librespot, e.g. using `start-stop-daemon`, the spotify desktop client does not stop streaming to the device as librespot does not properly close the connection and remove its Bonjour service.

**Comment by joerg-krause** [comment]
On closer examination librespots unregisters it service immediately after receiving its credentials as [`Drop()`](https://github.com/plietar/rust-mdns/blob/18df08221acdcdc8ef41af291f26afed2cdaea57/src/lib.rs#L146) is called for the `Responder` in [`discovery_login()`](https://github.com/plietar/librespot/blob/master/src/authentication/discovery.rs#L159-L189).

Not sure if this is correct or if the service should be unregister while closing librespot.

**Comment by plietar** [comment]
If the service isn't dropped after receiving its credentials, other devices logged in with a different account could send theirs as well.
Unfortunately, librespot doesn't support switching account, so that's why it unregisters itself immediately.

**Comment by joerg-krause** [comment]
I see! So, librespot does not need to unregister its service. However, how could it properly close the connection?
