### ISSUE TITLE
Windows build errors

### ISSUE THREAD

**Issue by CoDEmanX** [plietar/librespot#12]
The build fails and I can't track it down, because it's the build executable that fails. I assume it is compiled by another build script, but no idea how to fix it:

```
failed to run custom build command for `librespot-protocol v0.1.0
librespot\target\debug\build\librespot-protocol-39e21a77f117cd01\build-script-build`
(exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value:
IoError(Error { repr: Os { code: 2, message: "System can't find path specified." } })', 
../src/libcore\result.rs:688
```

**Comment by CoDEmanX** [comment]
I forgot to add the protobuf executables to PATH, doh!

```
set PATH=path\to\protoc.exe;path\to\protoc-gen-rust.exe;path\to\mingw\bin;%PATH%
```

I had to specify the path to gcc.exe as well, seems like something is hardwired to that compiler (most bits are compiled by msvc as far as I can tell).

But there are more build issues:
`copy_memory` does not exist anymore, and I tried to fix it like this in metadata.rs:

```
dst.clone_from_slice(&file.get_file_id()[..20]);
dst.clone_from_slice(&image.get_file_id()[..20]);
```

It compiles, but then complains about a missing 2nd type parameter:

```
let stream = portaudio::stream::Stream::<i16>::open_default(
```

I added a second i16, which suppresses the compile error at least. But now it fails because of 

```
note: ld: cannot find -lportaudio
```

:cry:

**Comment by CoDEmanX** [comment]
Figured it out: I need to place a portaudio DLL...

https://github.com/spatialaudio/portaudio-binaries or
https://github.com/adfernandes/precompiled-portaudio-windows

... into the Rust lib folder, e.g.

```
C:\Program Files\Rust nightly 1.7\lib\rustlib\x86_64-pc-windows-gnu\lib
```

It needs to be renamed to `portaudio.dll` in order to make the compiler (`ld.exe`) find it.

Another copy needs to be placed next to `main.exe`. It needs to be called differently here, depending on what name is compiled into the DLL (`portaudio_x64.bit`, `libportaudio-x86_64-w64-mingw32.static.dll` or something like that).

It compiles without error, there are only a couple warnings (which may turn into hard errors in future Rust versions however).

I can login to Spotify and the device name appears in the Connect device list, but it doesn't stay there. It keeps printing spirc notify messages from my real Connect speaker though. How is it supposed to behave?

**Comment by plietar** [comment]
Feel free to make a PR to add windows instructions.
I do have the same problem of the device disappearing immediately, I'll have to investigate.
I'm closing this issue since it is a different problem.

EDIT: should be fixed now :smile:

**Comment by CoDEmanX** [comment]
Got it to work, yay! The device still seems to disappear for a second when a song ends, but I'll need to test this more in-depth.

I'll do a PR for Windows for sure. How about to make the build script download the portaudio DLLs from aforementioned GitHub project automatically on Windows?

**Comment by crsmoro** [comment]
I went through all these errors, helped a lot, but i got one more and i dont know what to do, i have zero knowledge on rust

```
cargo build
   Compiling bitflags v0.3.3
   Compiling chunked_transfer v0.3.1
   Compiling ascii v0.5.4
   Compiling bit-vec v0.4.2
   Compiling pkg-config v0.3.6
   Compiling librespot-protocol v0.1.0
   Compiling libc v0.1.12
   Compiling protobuf_macros v0.1.1 (https://github.com/plietar/rust-protobuf-macros.git#ade4282d)
C:\Users\crist\.cargo\git\checkouts\rust-protobuf-macros-0155ebac4efea846\master\src/lib.rs:1:1: 1:45 error: #[feature] may not be used on the beta release channel
C:\Users\crist\.cargo\git\checkouts\rust-protobuf-macros-0155ebac4efea846\master\src/lib.rs:1 #![feature(plugin_registrar, rustc_private)]
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\crist\.cargo\git\checkouts\rust-protobuf-macros-0155ebac4efea846\master\src\util.rs:83:22: 83:24 error: slice pattern syntax is experimental (see issue #23121)
C:\Users\crist\.cargo\git\checkouts\rust-protobuf-macros-0155ebac4efea846\master\src\util.rs:83         Some((ident, [])) => (ident, parent),
   Compiling protobuf v1.0.10
                                                                                                                     ^~
error: aborting due to 2 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `protobuf_macros`.

To learn more, run the command again with --verbose.
```

**Comment by plietar** [comment]
@crsmoro you need to use the nightly rust channel, beta won't work

**Comment by crsmoro** [comment]
using nightly

```
Build failed, waiting for other jobs to finish...
failed to run custom build command for `dns-sd v0.1.1`
Process didn't exit successfully: `\GitHub\librespot\target\debug\build\dns-sd-a5a414e58e1f2a52\build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"avahi-compat-libdns_sd\"`: The system cannot find the file specified. (os error 2)"', ../src/libcore\result.rs:688
```

**Comment by crsmoro** [comment]
forcing to use 0.10 of dns-sd worked for that error..
but now i'm getting something related to protobuf, it says to run `rustc --explain E0425` that says 'unresolved name was used'.. there's more than a hundreds, one of them below...

```
librespot\target\debug\build\librespot-protocol-9a31e481398102fc\out/authentication.rs:1613:21: 1613:107 note: in this expansion of try! (defined in <std macros>)
protocol\src\lib.rs:7:1: 7:75 note: in this expansion of mod_path! (defined in protocol\src\lib.rs)
librespot\target\debug\build\librespot-protocol-9a31e481398102fc\out/authentication.rs:1613:26: 1613:68 help: run `rustc --explain E0425` to see a detailed explanation
librespot\target\debug\build\librespot-protocol-9a31e481398102fc\out/authentication.rs:1816:26: 1816:66 error: unresolved name `protobuf::rt::read_singular_bytes_into` [E0425]
librespot\target\debug\build\librespot-protocol-9a31e481398102fc\out/authentication.rs:1816                     try!(::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.public_key));
```

**Comment by crsmoro** [comment]
i really don't know what else to do, i've even removed everything and installed all over again.. in the end i'm still getting the error above..

**Comment by NeoLegends** [comment]
@CoDEmanX How did you get it to link? After compiling protobuf and linking to protobuf manually (via placing the dll in \Rust Installation Dir\lib\rustlib<Toolchain>\lib, I struggle to get `librespot-protocol` to link to libz (or rather `-lz`).

**Comment by CoDEmanX** [comment]
@NeoLegends: It's a while ago since I managed to compile it, and I haven't tried it again with a more recent version. Maybe it's broken on Windows at the moment.

**Comment by NeoLegends** [comment]
I'm coming from the managed world, so I have rather limited knowledge of native code compilation and toolchains, could you tell me how to go about finding and fixing the problems that are preventing the compilation on Windows?
