### ISSUE TITLE
http Streaming

### ISSUE THREAD

**Issue by mxschmitt** [plietar/librespot#120]
Hello,
Is it possible to "make" a http stream feature in librespot?

**Comment by plietar** [comment]
This would be outside the scope of the project.
I've just added a audio backend which allows redirecting the output into arbitrary files.
You should be able to use that to pipe into a 3rd party software to stream it over http

**Comment by mxschmitt** [comment]
Is the feature activated by using the pulseaudio feature?

**Comment by mxschmitt** [comment]
![image](https://cloud.githubusercontent.com/assets/17984549/21578143/f3c22b5a-cf75-11e6-854c-01e59a1715c3.png)

**Comment by plietar** [comment]
You need to update to a more recent version of rust

**Comment by mxschmitt** [comment]
Is the format something like wave and I need just to add the correct header?

Fixed through this Stackoverflow:
http://stackoverflow.com/questions/11986279/can-ffmpeg-convert-audio-from-raw-pcm-to-wav

**Comment by plietar** [comment]
Format is raw PCM, 16bit, native endian

**Comment by mxschmitt** [comment]
Here is an example for using the pipe feature:
##### What does it do?
- Starts an http audio stream on an given port and serves the audio from librespot
##### Requirements:
- ffmpeg
- vlc
- compiled librespot
#### More detailed instructions are in the header of the bash script 😃 
##### Bash Script:
- https://gist.github.com/maxibanki/e2ab50b9d68f983a6a48e56e0c5ba330

After the script has been started there should be an http audio stream (mp3) available on port :8081/stream.mp3

**Comment by plietar** [comment]
> compiled librespot with the pulseaudio backend

The pipe backend is always enabled, and does not require the pulseaudio backend

**Comment by sashahilton00** [comment]
@plietar is there any means by which one can access the metadata, or at least the track ID currently playing via a pipe (or other means)? Would be great for displaying current song info in another application
