### ISSUE TITLE
Panic on an `Err` value: InitialFileHeadersCorrupt

### ISSUE THREAD

**Issue by joerg-krause** [plietar/librespot#121]
Sometimes, librespot panics with:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InitialFileHeadersCorrupt', src/libcore/result.rs:799
```

This issue happens if a track is loaded in the Spotify Connect Client (so I can see the cover and the track artists and song title), but is not played locally (but was played before). Then I start librespot on my embedded Linux device, connect the client with librespot and after 3 or 4 seconds the panic happens.

Note, I am using Tremor as ogg decoder.

**Comment by joerg-krause** [comment]
Not sure why [OV_EINVAL](https://github.com/plietar/rust-tremor/blob/master/src/lib.rs#L266) is described as [InitialFileHeadersCorrupt](https://github.com/plietar/rust-tremor/blob/master/src/lib.rs#L36) whereas  [vorbis-errors](http://www.fifi.org/doc/libvorbis-dev/vorbis-errors.txt) describes it as:

> OV_EINVAL       Invalid argument value.

**Comment by herrernst** [comment]
Hm, I've just cross-compiled the current master for Raspberry Pi and *always* got `InitialFileHeadersCorrupt`, not yet found out the cause (not using Tremor btw)

**Comment by joerg-krause** [comment]
Maybe this one helps: https://github.com/joerg-krause/librespot/commit/b58dc0b54e719101205dcd972062334cc72849db

**Comment by plietar** [comment]
I've cherry picked @joerg-krause's commit (thanks btw).
Since I can't reproduce this I'm not too sure how to fix the root cause.

**Comment by joerg-krause** [comment]
Closed due to lack of maintenance of the project.
