### ISSUE TITLE
Error when building as dependency

### ISSUE THREAD

**Issue by wlcx** [plietar/librespot#133]
Similar to #94, Builds of a project using librespot as a dependency fail for me, with the following error:
```
error[E0432]: unresolved import `self::portaudio::PortAudioSink`
   --> /home/samw/prog/rust/spot/target/debug/build/librespot-1aab42d688af77d7/out/lib.rs:971:9
    |
971 |     use self::portaudio::PortAudioSink;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PortAudioSink` in `audio_backend::portaudio`
```

This includes  https://github.com/plietar/spotsync, which I have been using to test, **but only when the committed cargo.lock is deleted**. I have tried pinning my dependency of librespot to the version in spotsync's cargo.lock (a9ae5b50) but the same error occurs.

OS: arch linux
Rust: both current stable and nightly

my cargo.toml: 
```
[package]
name = "test"
version = "0.1.0"
authors = ["Sam Willcocks <sam@wlcx.cc>"]
 
[dependencies]
termbox = "*"

[dependencies.librespot]
git = "https://github.com/plietar/librespot"
```

**Comment by dmfutcher** [comment]
Seeing the same issue with building respot as a dependency on Arch. Anyone managed to work out how to solve this?
