### ISSUE TITLE
Since today not working anymore

### ISSUE THREAD

**Issue by lassos** [plietar/librespot#136]
Hi. I have changed nothin in system. Since today the librespot do not run anymore -> see error below

Maybe spotify has changed their api. On the developer page i have found:

The libspotify key generation and retrieval service has been deprecated, along with libspotify.
You may apply to get a key using our App-key Request Form for private, individual usage. Bear in mind that you should do no new development using libspotify.

```
:/etc/init.d# RUST_BACKTRACE=1 /usr/bin/librespot /home/XXX/librespot/spotify_appkey.key --username XXXX --password XXX --bitrate 320 --name XXXX --backend pulseaudio
INFO:librespot::main_helper: librespot 6fa4e4d (2016-09-21). Built on 2016-10-27.
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax("expected value", 1, 1)', ../src/libcore/result.rs:746
stack backtrace:
   1: 0xb75ffa9c - sys::backtrace::tracing::imp::write::hcd9c6b761d959e16Xcv
   2: 0xb76026c1 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44492
   3: 0xb76022bd - panicking::default_handler::hda9238d9f8e0ef0alSz
   4: 0xb75ee6c9 - sys_common::unwind::begin_unwind_inner::h7224040aaffdbb98g1t
   5: 0xb75eebd7 - sys_common::unwind::begin_unwind_fmt::h9d1eda8fc60b8ae3m0t
   6: 0xb75fedf1 - rust_begin_unwind
   7: 0xb7632b40 - panicking::panic_fmt::h559080aff49c30cclcM
   8: 0xb72726ae - result::unwrap_failed::h17532309936106461326
   9: 0xb7271dbd - apresolve::apresolve::h88b22a7087faf0d6m2a
  10: 0xb731ce26 - session::Session::login::h28aec440ed3c27dbi8d
  11: 0xb7235d94 - main::he68e52d52f3260a9Iba
  12: 0xb7601f3a - sys_common::unwind::try::try_fn::h10144795978809605109
  13: 0xb75fed27 - __rust_try
  14: 0xb76019f9 - rt::lang_start::he74f855a6a899d05rKz
  15: 0xb7240dfd - main
  16: 0xb7059e45 - <unknown>
```

**Comment by funtax** [comment]
Hey, Spotify's https://apresolve.spotify.com is down since yesterday and
they have the same issue on their own clients.

With a hardcoded backend everything is still ok, no worries :-)

**Comment by funtax** [comment]
Change your password! !

Am 30.12.2016 10:58 vorm. schrieb "lassos" <notifications@github.com>:

**Comment by lassos** [comment]
thank you so much .-))))))

glad to hear . Ups,. Yes. Shit. Yes i will change it

**Comment by lassos** [comment]
funtax, could you please edit your quote ? There is the password and username. So i edited my post too 

thank you .-))))

**Comment by funtax** [comment]
Of course. Keep in mind that your credentials have been sent via e-mail and other channels.

**Comment by lassos** [comment]
Yes. Of course , i have changed password .-)

**Comment by plietar** [comment]
Thanks for the report, I've pushed a fix to use a fallback AP. That's what the desktop client seems to do.
