### ISSUE TITLE
Fallback error compiling

### ISSUE THREAD

**Issue by lassos** [plietar/librespot#137]
Thanks for the fallback function. Compiling getting error:

   Compiling librespot-protocol v0.1.0 (file:///home/XXX/librespot/librespot)
protocol/build.rs:16:36: 16:37 error: expected one of `.`, `;`, or an operator, found `?`
protocol/build.rs:16     let mut file = File::open(path)?;
                                                        ^
error: aborting due to previous error

**Comment by plietar** [comment]
You probably need to update to the latest rust stable

**Comment by lassos** [comment]
thanks. yes, updated rust version works. but new install comes with errors, any ideas ? 

multihome:/home/lars/librespot/librespot# cargo build --release
   Compiling librespot v0.1.0 (file:///home/lars/librespot/librespot)
error[E0432]: unresolved import `self::portaudio::PortAudioSink`
   --> /home/lars/librespot/librespot/target/release/build/librespot-d8566a9c9f4b772e/out/lib.rs:998:9
    |
998 |     use self::portaudio::PortAudioSink;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PortAudioSink` in `audio_backend::portaudio`

error: aborting due to previous error

error: Could not compile `librespot`.

##########

multihome:/home/lars/librespot/librespot# cargo build --features pulseaudio-backend
   Compiling librespot v0.1.0 (file:///home/lars/librespot/librespot)
error[E0432]: unresolved import `self::portaudio::PortAudioSink`
   --> /home/lars/librespot/librespot/target/debug/build/librespot-d8566a9c9f4b772e/out/lib.rs:998:9
    |
998 |     use self::portaudio::PortAudioSink;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PortAudioSink` in `audio_backend::portaudio`

error[E0432]: unresolved import `self::pulseaudio::PulseAudioSink`
    --> /home/lars/librespot/librespot/target/debug/build/librespot-d8566a9c9f4b772e/out/lib.rs:1002:9
     |
1002 |     use self::pulseaudio::PulseAudioSink;
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PulseAudioSink` in `audio_backend::pulseaudio`

error: aborting due to 2 previous errors

error: Could not compile `librespot`.

To learn more, run the command again with --verbose.

**Comment by lassos** [comment]
OK. Got it. Deleted all files. Cloned new . 

 cargo build --release --features "pulseaudio-backend"

worked for me

**Comment by plietar** [comment]
This is similar to #133, I still need to look into it.
You probably ran `cargo update` which caused it.

Closing since it's working for you now.

**Comment by mfonville** [comment]
I hit the same initial issue, with the rust version from Ubuntu 16.10;
```
 error: the `?` operator is not stable (see issue #31436)
```
when checking the bugreport, `?` seems not to be fully implemented yet (but it is for this use case); so why not use the `try!` statement instead?

**Comment by kyrias** [comment]
it's not that it's not fully implemented, it's that it hasn't been marked stable yet, so requires a nightly compiler for now.

**Comment by plietar** [comment]
It has been marked stable since Rust 1.13, released in November 2016.
Supporting older rust versions is not a priority for me, as long as the latest stable works. I would accept a PR to change `?` to `try!` though.

Note that Rust 1.15 is due next month, and I am planning on using some of its features, so I'm not committing to support any specific rust version. You should update to the latest one.

**Comment by mfonville** [comment]
@plietar thanks for your explanation.
I understand your reasons, and especially while the project is still young and taking advantage of new rust features. But it would be nice if at least at some point in the future,  only features of a rust version that can be found in major distributions' repositories would be used, to make it more easy to run the tool or make it packageable.

**Comment by kyrias** [comment]
(Ah, missed that it had been stabilized, and seems like it builds cleanly on 1.14.0 for m.)

**Comment by kyrias** [comment]
Also, Arch is on 1.14, Debian Stretch is on 1.13, Debian Sid is on 1.14, Fedora 24/25 is on 1.13, Fedora Rawhide is on 1.14.  So it's pretty safe to say that it should work on the rust version distributed by major distributions. :p
