### ISSUE TITLE
librespot as a systemd service - less chatty by default

### ISSUE THREAD

**Issue by arigit** [plietar/librespot#141]
Using librespot as systemd service, with the default recommended options (herrernst binary for raspberry)
Very quickly the journal fills up with librespot output such as

librespot::audio_file2: Got channel 30
....

This can be fixed in the systemd service definition by adding
 > /dev/null 2>&1 &

However this mutes all output; and since librespot is mature, wouldn't it make sense for it to by less chatty by default - just output the key messages important to the log such as 
started
authenticated
started playing 
stopped playing 

and activate all the current "debug" info (chunk downloads, volume changes etc) only when passed a --verbose command line option

**Comment by herrernst** [comment]
You can reduce log level by setting RUST_LOG environment variable to the desired level: https://doc.rust-lang.org/log/env_logger/
I recommend adding this line in the [Service] section of the systemd unit:
```Environment="RUST_LOG=info"```

**Comment by plietar** [comment]
Agreed, that was too verbose. Thanks for opening the issue.
I've changed the default level to `info`, with a `--verbose` argument to switch to `trace`.
The `RUST_LOG` environment variable still can still be used as well.
