### ISSUE TITLE
Unable to complie in RaspberryPi (armv7l Raspbian GNU/Linux 8)

### ISSUE THREAD

**Issue by RafaPolit** [plietar/librespot#147]
I am trying to compile librespot on a RaspberryPi (armv7l Raspbian GNU/Linux 8), but it fails to move past syntex_syntax v0.52.0 (previous versions of the same package compile correctly).

This is the output:

`$ cargo build --release --features alsa-backend`

   Compiling language-tags v0.2.2
   Compiling protobuf v1.0.24
   Compiling vorbisfile-sys v0.0.8
   Compiling dtoa v0.2.2
   Compiling unicode-normalization v0.1.3
   Compiling rand v0.3.15
   Compiling liblmdb-sys v0.2.1
   Compiling typeable v0.1.2
   Compiling idna v0.1.0
   Compiling uuid v0.2.3
   Compiling num-bigint v0.1.35
   Compiling url v1.2.4
   Compiling num-rational v0.1.35
   Compiling lmdb-rs v0.7.3
   Compiling num v0.1.36
   Compiling bitflags v0.4.0
   Compiling nix v0.5.1
   Compiling nix v0.7.0
   Compiling bit-set v0.4.0
   Compiling vorbis-sys v0.0.8
   Compiling vorbis-encoder v0.1.4
   Compiling url v0.5.10
   Compiling vorbis v0.1.0
   Compiling tempfile v2.1.4
   Compiling cookie v0.2.5
   Compiling vergen v0.1.1
   Compiling syntex_syntax v0.44.1
   Compiling eventual v0.1.7
   Compiling hyper v0.9.14
   Compiling mio v0.6.2
   Compiling tokio-core v0.1.2
   Compiling mdns v0.2.0 (https://github.com/plietar/rust-mdns#2078310b)
   Compiling syntex_syntax v0.50.0
   Compiling rust-crypto v0.2.36
   Compiling serde_json v0.8.4
   Compiling librespot-protocol v0.1.0 (file:///home/pi/src/librespot/protocol)
   Compiling syntex_syntax v0.52.0

---
Any ideas where to begin? Is it imposible to have some pre-compiled binaries?

Thanks,
Rafa.

**Comment by plietar** [comment]
Thanks for the report.
One of the last dependencies on that list, `librespot-protocol` is pretty large and can take a while to build. That dependency alone takes about four minutes on my laptop, so probably a lot more on a pi. A debug build will be significantly faster to compile, but fast enough to run even on a pi.

@herrernst maintains pre-compiled binaries for raspberry pis : https://github.com/herrernst/librespot/releases

**Comment by RafaPolit** [comment]
Thanks for the info!

Maybe the useful fork can be included in the README? Still havent been able to compile on the RPi3.  Its just the syntex_syntax v0.52.0, it doesn't matter the order of compiling, when it reaches the syntex, it stops, and then, after a few minutes (more than 20) the Pi is not even responding at all, needs to be uplugged and reset.

Any further ideas? Thanks.
Rafa.

**Comment by ITAtAnki** [comment]
Rafael,

I found that I had to give my RPI some (200mb) swap space
via dphys-swapfile to get that dependency comping correctly. I saw my
system maxing out on memory trying to build it in combination with running
other services I had running at the time.

You might try monitoring your memory utilization while building and if you
see your system hitting OOM, you might try a bit of swap.

**Comment by superlupo12** [comment]
Which Raspberry Pi do you have? I guess 2 or 3, because your architecture is armv7. Those have 4 cores, and cargo uses 4 threads (or processes) to build as fast as possible. Maybe your power supply is too weak for a long all-cpu strain. Maybe also memory runs out and your system doesn't deal quite well with it. I suggest trying to build with less parallelism. Add `-j 2` or even `-j 1` to your `cargo build` command, like `cargo build --release --features alsa-backend -j 2`. Takes twice or four times as long, but uses less memory and cpu at a time. And/or you could change the GPU memory split so your system has more memory.

@marcust even provides debian packages for RPis: https://www.dropbox.com/sh/euhswcu6xy9s6ht/AACHjlUCh61XYgzuhNB4AIGwa

Btw, @plietar, one thing that started puzzling me some weeks ago was that at least three different versions of syntex_syntax are built, is this necessary by the dependencies or some Cargo.lock-merge gone awry?

**Comment by RafaPolit** [comment]
Great info! Not really used to hitting those limits with large systems, obviously working with the RPi (yes the 3 for me) adds this to the mix.

Thanks guys.
Rafa.

ps. Yes, three different versions of syntex_syntax are being compiled for me as well.

**Comment by plietar** [comment]
> Maybe the useful fork can be included in the README

I don't want to endorse binaries built by a third party on the README

About syntex, three different dependencies (serde, json_macros and protobuf_macros) need it, but it is a very volatile dependency which breaks compatibility very often.
I control the two _macros dependencies and I sync them up to the latest version of syntex every now and then. syntex is only used at build time, so there isn't much incentive for me to do the work.

Note that serde will soon (rust 1.15, 3rd of Feb) not need syntex anymore, so it's authors have stopped keeping up with syntex changes.

**Comment by RafaPolit** [comment]
Thanks @plietar, maybe then a hint or FAQ to this issues on lower hardware and limiting the cores?

Ok, thanks @ITAtAnki  and @superlupo12:  success building with -j 2 on Rpi3 with some other tasks running in backround, no need to change the swap space to what was already assigned (to moOde Os, a Raspbian-based distro).

Thanks again, great tip.  Best regards,
Rafa.
