### ISSUE TITLE
thread 'main' panicked at 'Box<Any>', src/session.rs:115

### ISSUE THREAD

**Issue by joerg-krause** [plietar/librespot#156]
Running the latest master works great so far! Yesterday, I set up a playlist in the Spotify App lo be played in a loop and selected the librespot client as audio sink. When I woke up today, the librespot client died:

```
DEBUG:librespot::audio_file: File 774f64e3c9690d01ecad1a35ed0bde12d978dfae complete
DEBUG:librespot::session: Session[0] strong=3 weak=6
DEBUG:librespot::player: command=Load(SpotifyId(u128 { high: 8492558088775026015, low: 11919394522851906758 }), true, 0)
DEBUG:librespot::session: drop Dispatch
thread 'main' panicked at 'Box<Any>', src/session.rs:115
```

**Comment by joerg-krause** [comment]
I am able to reproduce the panic when I force a disconnection of my DSL connection in the router. The librespot client keeps streaming fine after the router get a new IP. However, the Spotify App drops connection to the client. The status bar goes from green to blue., but the device is in the list and  selectable. If I select the device now, librespot panics.

**Comment by joerg-krause** [comment]
The error message is "Connection reset by peer". Ideally, we should try to reconnect. Unfortunately, I have no idea, how to do it for librespot.

When this event happens, the Spotify Player disconnects for a moment from the librespot device (the status bar goes from green to blue for a short moment) than the device is displayed as connected again for about 2 or 3 seconds. Thereafter, the player shows the device as disconnected.

**Comment by bowiz2** [comment]
Have the same issue when playing from the Android client. Passing a username and using the --disable-discovery flag allowed me to connect from my phone, but after about 1.5 - 2 minutes, the connection was dropped, while librespot still showed nothing out of the ordinary.

After the connection was dropped, I couldn't reconnect to librespot, as it still thought it was connected to the client.

I received a similar
`thread 'main' panicked at 'Box<Any>', src/session.rs:83`
error after about 5 minutes.

Build info:
`INFO:librespot: librespot ddfc28f (2017-08-04). Built on 2017-08-07. Build ID: N5RcEuis
`
Running on a Raspberry Pi 1

**Comment by joerg-krause** [comment]
Closed due to lack of maintenance of the project.
