### ISSUE TITLE
Add support for Facebook based login

### ISSUE THREAD

**Issue by plietar** [plietar/librespot#16]

**Comment by plietar** [comment]
Done (4b4bc2f).
See instructions in the README.

**Comment by eladnava** [comment]
Hi @plietar,
Thanks for your work on this! Although I see that Facebook auth support has been removed:
https://github.com/plietar/librespot/commit/e254bb7291319efb0dc58dd4aa2c621a2b12fd8f

Although the `authentication.md` still mentions it:
https://github.com/plietar/librespot/blob/1e652b1a7ee7ba8d491938517a7db84c2a974f17/docs/authentication.md#facebook-based-authentication

Is it still possible to authenticate with a Facebook account?

**Comment by plietar** [comment]
@eladnava I removed Facebook support because it required ssl, which led to issues when cross compiling. Additionally it was not used much. `authentication.md` describes the protocol, not my implementation so I left it there.

You can use discovery mode even with a Facebook account, or I think you can generate a user id with can be used as a username (I don't know how though).

Note that I've stopped maintaining librespot, see the README.

**Comment by eladnava** [comment]
@plietar Cool, thanks, and appreciate all the work you put into this. 💯
