### ISSUE TITLE
Panic with message "No space left on device"

### ISSUE THREAD

**Issue by joerg-krause** [plietar/librespot#166]
When playling long tracks on my embedded device with about 36MB of free RAM, librespot panics with: `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 28, message: "No space left on device" } }'`.

For example using [this](https://open.spotify.com/track/0Kbvz9ZjihrcE1Vd1dDCZh) track (45:31). Is there a way not to load the whole song into RAM?

**Comment by plietar** [comment]
Interesting, I never really considered very large tracks.
librespot doesn't load the whole song into RAM, but it downloads it into `/tmp`, which may be the same thing if that is mounted as a tmpfs.

As a temporary workaround, you can change [this line from `NamedTempFile::new()`](https://github.com/plietar/librespot/blob/eb49ff34f1fa5aa032d71573cb91101f315c1a34/src/audio_file.rs#L68) to `NamedTempFile::new_in("/somewhere/not/in/ram")`.

Ideally, if a cache directory is specified we can just use `$CACHE/temp` automatically for that.

**Comment by joerg-krause** [comment]
Thanks, I will try this. In fact, this track is an extreme. It my also happen for tracks having a length of six or seven minutes, depending on the free RAM left.

**Comment by joerg-krause** [comment]
On second thought, my system is NAND flash based. So, using anything else than the RAM for caching is not a good idea. So, I need a bigger RAM?

**Comment by plietar** [comment]
Pretty much. A solution would be to change `librespot` to break up the files in blocks of say 500KB, and delete them automatically (if cache is disabled) once it has moved on to the next one. This is a large-ish change, so it's unlikely I'll be able to implement it anytime soon unfortunately.

**Comment by michaelherger** [comment]
I've modified librespot to disable the audio file-cache. See pull request #181.

**Comment by joerg-krause** [comment]
Closed due to lack of maintenance of the project.
