### ISSUE TITLE
Poor error message when using free account

### ISSUE THREAD

**Issue by moon-chilled** [plietar/librespot#167]
I get `thread 'main' panicked at 'Authentication failed', /home/elronnd/librespot/target/debug/build/librespot-dfbb8235c1536a0f/out/lib.rs:365` when I try to run it.  I'm running with

    RUST_BACKTRACE=1 ./librespot -n "name" -u username -p password

[Backtrate](https://files.catbox.moe/fzvuvf.txt).

**Comment by plietar** [comment]
I'm not really sure what could be causing the `Authentication failed` other than well an incorrect password. Are you using a free account ? librespot only works with premium.
cc @kcning

**Comment by kcning** [comment]
Yes I'm using a free account. It's probably the cause.

**Comment by rdscorreia74** [comment]
There is absolutely no way to realize that librespot needs a Spotify premium account in order to work.
Could you please add it to the readme so that others don't make the same mistake I did?
Oh, and thanks for making librespot and for sharing it with us. :-)
Cheers

**Comment by eladnava** [comment]
@john3voltas I submitted a PR: #259.
