### ISSUE TITLE
Creating dylib objects fails

### ISSUE THREAD

**Issue by dbischof90** [plietar/librespot#183]
I'm trying to compile a *.dylib with cargo - on this way one could start interfacing the actual library from other languages like Ruby or Python.

This unfortunately fails due to vorbis-encoder (it seems that there are some multiple definitions of functions?). Since I haven't touched Rust until yesterday, I'm a little bit lost about what to do. But this seems to be essential.

**Comment by ferm10n** [comment]
Out of curiosity what method were you using to build the dylib?
