### ISSUE TITLE
Spotify now blocking librespot ?

### ISSUE THREAD

**Issue by marcelveldt** [plietar/librespot#190]
I might be mistaken but it seems that Spotify has taken some action to block Librespot as of yesterday my local time). I now have seen multiple users with the same issue.

INFO:librespot: librespot 07b46a8 (2017-05-16). Built on 2017-05-18.
INFO:librespot::session: Connecting to AP "gew1-accesspoint-a-6rrt.ap.spotify.com:4070"
thread 'main' panicked at 'Authentication failed', C:\Workdir\librespot\target\release\build\librespot-6090a773c19c0430\out/lib.rs:365
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: main
   5: main
   6: main
   7: _FILE_LINE
   8: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
   9: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  10: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  11: BaseThreadInitThunk

**Comment by maxx** [comment]
I've been experiencing this tonight as well.. assumed it was a temporary outage, but sounds like not.

**Comment by maxx** [comment]
I confirmed on both arm and amd64 linux builds

**Comment by cortegedusage** [comment]
+1.  librespot panics as stated above.

**Comment by plietar** [comment]
Indeed, I've "fixed" it in 29d5f794d623a27b651513b3fca8dbc9b1ca7341. It's only a matter of time until this gets blocked again unfortunately.

**Comment by kenciroz** [comment]
I've been experiencing the same error... It's such a shame if they are blocking It

**Comment by marcelveldt** [comment]
@plietar thanks! amazing work!

**Comment by funtax** [comment]
The "fix" was modifying the system_information_string to a new value.
Anyone knows what's used by official clients?

`system_information_string: "This is not the client you are looking for".to_owned(),`

**Comment by plietar** [comment]
On my machine the desktop client is using `system_information_string: "OS X 10.12.0 [x86 4]"`.

Eventually I'll change librespot to match this. I'm just seeing what's Spotify's reaction time

**Comment by sashahilton00** [comment]
I've sent them an email asking for clarification as to why they have blocked it and if it is due to a specific issue with librespot. Will let you know when I get a reply...

**Comment by maxx** [comment]
Is there anything else besides this string which can be used to identify librespot? user agent or anything?

**Comment by sashahilton00** [comment]
I'm sure they'll find a way if they really want to block it. E.g. Librespot doesn't support context so perhaps Spotify could check if a client supports context and then drop the connection if it doesn't... There's nothing that Spotify can do to prevent Librespot mimicking official clients in the long run, though obviously it would be preferable to reach an agreement with them...

**Comment by mfonville** [comment]
Maybe it would be an idea to check how 'relatively dumb'-clients like headless players (chromecast, sonos etc) identify themselves, it might be easier than trying to mimic the desktop client if they'd make it hard.

**Comment by sashahilton00** [comment]
I think we just leave it be until Spotify blocks it again... One could always just send a random uuid on each startup, I imagine having to keep a whitelist of clients would be nigh on impossible...

**Comment by maxx** [comment]
I think a lot of the dumb headless players out there have less or equivalent capability as librespot.. but as you said, that would be good to confirm .. especially on older non-updatable hardware.  I don't see it likely they'll start cutting those off.

I'm pretty disappointed that Spotify decided to do this -- this was one of the reasons I switched over to the service in the first place.

**Comment by sashahilton00** [comment]
I said as much in the email, strikes me as a somewhat idiotic middle management decision, unless they are planning on finally releasing a connect library...

**Comment by davidwmartin** [comment]
Tried the above fix (manually in file: /home/pi/librespot/target/release/build/librespot-52336aa0b4fb7baa/out/lib.rs) -- do I actually need to fully rebuild? Or should that have fixed things?

**Comment by maxx** [comment]
@davidwmartin you will need to rebuild - as it's currently implemented, string ends up in the binary.

**Comment by davidwmartin** [comment]
@maxx many thanks

**Comment by cortegedusage** [comment]
I Just tried, and now it seems to work again!

**Comment by gustafekeberg** [comment]
Working here too.

**Comment by sashahilton00** [comment]
I've been speaking with Spotify about this, they confirmed that they have resolved the issue and that librespot is confirmed to work once again, and they have said that they will get back to me with more info as to why it was blocked.

**Comment by joerg-krause** [comment]
Glad they answered and they did not meant to block it intentionally.

**Comment by sashahilton00** [comment]
Not sure whether it was intentional or not, still waiting on details. Glad they have unblocked for now though :)

**Comment by maxx** [comment]
It seems very specific to be unintentional! Curious to hear the followup.

**Comment by atze09** [comment]
Hey guys,
can anyone share his librespot.arm compiled for RPi3 please?
I stuck at compiling..

**Comment by cortegedusage** [comment]
https://github.com/herrernst/librespot/releases

Op 23 jun. 2017 10:25 a.m. schreef "atze09" <notifications@github.com>:

**Comment by atze09** [comment]
Is this suitable for snapcast with stdout-backend?

**Comment by cortegedusage** [comment]
Not sure, but I believe it is..

Op 23 jun. 2017 1:27 p.m. schreef "atze09" <notifications@github.com>:

**Comment by atze09** [comment]
i have tried your version, but it doesnÄt connect in spotify app, seems it crashes.
Which librespot version are you using?
The latest, with the spotify fix integrated?

**Comment by tatoosh** [comment]
I got the same problem by using the newest version (v20170709-aa86ebf)


```
INFO:librespot::session: Connecting to AP "lon3-accesspoint-a38.ap.spotify.com:4070"
thread 'main' panicked at 'Authentication failed', /home/travis/build/herrernst/librespot/target/arm-unknown-linux-gnueabihf/release/build/librespot-cbf31f11fa905ab0/out/lib.rs:365
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Bebowi** [comment]
Is it possible spotify has blocked librespot again? I could use it without any trouble a few days ago. Now I'm not able to Authenticate. 
`INFO:librespot::session: Connecting to AP "lon3-accesspoint-a56.ap.spotify.com:4070"
thread 'main' panicked at 'Authentication failed', /home/librespot/target/release/build/librespot-1e5c91a4a0e62319/out/lib.rs:365
`

**Comment by davidwmartin** [comment]
@Bebowi -- there was an issue that cropped up a few days ago (unrelated) -- 

https://github.com/plietar/librespot/issues/206 

Updating to latest build seems to have solved it.

**Comment by derWeihnachtsmann** [comment]
Changing the system information string fixed it..

**Comment by Bebowi** [comment]
@davidwmartin -- I've updated but error still occours

@derWeihnachtsmann -- Where can I change it?

**Comment by maxx** [comment]
@Bebowi: here https://github.com/plietar/librespot/blob/master/src/connection/mod.rs#L44

I bet changing it back to 'librespot' (undoing https://github.com/plietar/librespot/commit/29d5f794d623a27b651513b3fca8dbc9b1ca7341) would also suffice.

**Comment by sashahilton00** [comment]
https://github.com/plietar/librespot/pull/207 should fix it, it's just waiting on a merge, or possibly for someone to add the code which adds a random 8 character alphanumeric string to the end of it instead of the date. Spotify were pretty clear when I spoke with them that they wanted it to identify as librespot_[short_sha]_[random 8 character alphanumeric], so this is probably just them bumping things along...
