### ISSUE TITLE
What is the "--name" parameter?

### ISSUE THREAD

**Issue by Runemoro** [plietar/librespot#205]
Librespot is asking me to put a "--name" parameter to use it. What am I supposed to put in it? I tried a random string but that's giving me "Authentification failed":

```
...\librespot-master\target\release\build\librespot-7be9d501dda47e35\out/lib.rs:365
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: tokio_signal::ctrl_c
   5: tokio_signal::ctrl_c
   6: tokio_signal::ctrl_c
   7: tokio_signal::ctrl_c
   8: _FILE_LINE
   9: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  10: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  11: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  12: BaseThreadInitThunk
```

I've compiled it myself on Windows but had to remove mdns and comment out sections related to discovery, because mdns wouldn't compile. Could that be why? Or does name have to be something specific?

**Comment by herrernst** [comment]
The name parameter is just how this Spotify Connect instance is called and will appear in the Spotify app, it can be mostly anything (except maybe some problems with special characters). 

If you disable discovery, you have to pass --username with your Spotify username and then enter the password in the interactive prompt.

**Comment by shanemeagher** [comment]
@Runemoro Regarding the "Authentication Failed" error, are you using a free account? Only Premium accounts work with Spotify Connect. See issue https://github.com/plietar/librespot/issues/167

**Comment by Runemoro** [comment]
@shanemeagher Yes, I'm using a free account. :( Will those be supported in the future?

**Comment by sashahilton00** [comment]
I doubt it, I suspect quite a few people buy Premium for Connect functionality. That decision rests with Spotify, this library just mirrors the restrictions imposed by Spotify. If they decide to change it, librespot will be changed alike.
