### ISSUE TITLE
librespot as replacement for libspotify on win32

### ISSUE THREAD

**Issue by thomassteen** [plietar/librespot#209]
Sorry if this has already been covered, but now that the official libspotify is shut down, and audio systems relying on that (Beosound 5 to name one) is no longer functional, I am wondering if it would be possible to compile librespot to a one to one clone for libspotify.dll? Then I could replace the libspotify.dll on my Beomaster 5 and it would come back to life :-)

Thanks,
Thomas.

**Comment by plietar** [comment]
Unfortunately, while it would be possible to make a C wrapper around librespot, making it compatible with libspotify would be very hard, as the two libraries have different internal designs.

I gave it a try a while ago but gave up and eventually removed it from the tree, see https://github.com/plietar/librespot/tree/4d277e5b757f2bd4f8512f43316a28402410075d/capi
