### ISSUE TITLE
Connecting to librespot shows an error and pressing play crashes libreSpot

### ISSUE THREAD

**Issue by pwielders** [plietar/librespot#214]
It was working for several days correctly. Now all of a sudden I receive an error.

RUST_BACKTRACE=1 librespot --backend pipe --bitrate 320 --cache /tmp --device /home/pierre/SpotControl/rawpcm.pipe --name TestDevicePierre --username pierre.wielders -v
INFO:librespot: librespot 67deb07 (2017-06-30). Built on 2017-07-03.
INFO:librespot::session: Connecting to AP "gew1-accesspoint-b-kl7n.ap.spotify.com:4070"
INFO:librespot::session: Authenticated as "pierre.wielders" !
DEBUG:librespot::session: new Session[0]
DEBUG:librespot::spirc: new Spirc[0]
DEBUG:librespot::mercury: new MercuryManager
DEBUG:librespot::player: new Player[0]
DEBUG:librespot::session: Session[0] strong=3 weak=2
INFO:librespot::session: Country: "NL"
DEBUG:librespot::mercury: subscribed uri=hm://remote/3/user/pierre.wielders/ count=0
DEBUG:librespot::spirc: kMessageTypeNotify "Talkie" 7b085f5c29e45348a84b6f466a3419397bf3b112 1 1499690326708
DEBUG:librespot::spirc: kMessageTypeNotify "Huiskamer" RINCON_000E5832D91401400:3019725940 746771385 0
DEBUG:librespot::spirc: kMessageTypeHello "Talkie" 7b085f5c29e45348a84b6f466a3419397bf3b112 214 1499690326708
DEBUG:librespot::spirc: kMessageTypeNotify "TestDevicePierre" 9ac65ca60689683944cd3623cf1456898d67ffe5 2 1499690366053
DEBUG:librespot::spirc: kMessageTypeNotify "Huiskamer" RINCON_000E5832D91401400:3019725940 746780474 0
DEBUG:librespot::spirc: kMessageTypeLoad "Talkie" 7b085f5c29e45348a84b6f466a3419397bf3b112 2 0
DEBUG:librespot::player: command=Load(SpotifyId(u128 { high: 8530764249892212396, low: 9463195310723833724 }), false, 41749)
DEBUG:librespot::metadata: new MetadataManager
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: WireError("invalid value for enum: 12")', src/libcore/result.rs:837
stack backtrace:
   1:     0x55d0c92b405a - std::sys::imp::backtrace::tracing::imp::write::hd9cb4c1797101742
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55d0c92b8e4f - std::panicking::default_hook::{{closure}}::h154dea97b11a961f
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:349
   3:     0x55d0c92b8a54 - std::panicking::default_hook::h7b2373844128ce08
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:365
   4:     0x55d0c92b92f7 - std::panicking::rust_panic_with_hook::h8d52d23c1df454da
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:553
   5:     0x55d0c92b9134 - std::panicking::begin_panic::h031e0a076e248818
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:515
   6:     0x55d0c92b90a9 - std::panicking::begin_panic_fmt::hcd972326ec953c01
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:499
   7:     0x55d0c92b9037 - rust_begin_unwind
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:475
   8:     0x55d0c92f0aad - core::panicking::panic_fmt::h519452995771b90d
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libcore/panicking.rs:69
   9:     0x55d0c8fd28c7 - core::result::unwrap_failed::hdb09985b144a6c52
  10:     0x55d0c8fb3b79 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h9aa2d383a958cbbb
  11:     0x55d0c903a132 - librespot::player::PlayerInternal::load_track::h8aca7b54fea8c11e
  12:     0x55d0c9036b57 - librespot::player::PlayerInternal::run::he7bebf564314b16f
  13:     0x55d0c8f95d70 - std::panicking::try::do_call::h200c5d0e523a30a0
  14:     0x55d0c92c1c7a - __rust_maybe_catch_panic
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libpanic_unwind/lib.rs:98
  15:     0x55d0c8f9a65c - <F as alloc::boxed::FnBox<A>>::call_box::he317414d546fe35a
  16:     0x55d0c92b8134 - std::sys::imp::thread::Thread::new::thread_start::hc88703e10b184eab
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/liballoc/boxed.rs:615
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/sys_common/thread.rs:21
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/sys/unix/thread.rs:84
  17:     0x7ffbee6096b9 - start_thread
  18:     0x7ffbee33f3dc - clone
  19:                0x0 - <unknown>
DEBUG:librespot::player: drop Player[0]
DEBUG:librespot::spirc: kMessageTypeNotify "TestDevicePierre" 9ac65ca60689683944cd3623cf1456898d67ffe5 3 1499690367589
DEBUG:librespot::spirc: kMessageTypeNotify "Talkie" 7b085f5c29e45348a84b6f466a3419397bf3b112 215 1499690326708
DEBUG:librespot::spirc: kMessageTypePlay "Talkie" 7b085f5c29e45348a84b6f466a3419397bf3b112 3 0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:837
stack backtrace:
   1:     0x55d0c92b405a - std::sys::imp::backtrace::tracing::imp::write::hd9cb4c1797101742
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55d0c92b8e4f - std::panicking::default_hook::{{closure}}::h154dea97b11a961f
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:349
   3:     0x55d0c92b8a54 - std::panicking::default_hook::h7b2373844128ce08
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:365
   4:     0x55d0c92b92f7 - std::panicking::rust_panic_with_hook::h8d52d23c1df454da
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:553
   5:     0x55d0c92b9134 - std::panicking::begin_panic::h031e0a076e248818
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:515
   6:     0x55d0c92b90a9 - std::panicking::begin_panic_fmt::hcd972326ec953c01
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:499
   7:     0x55d0c92b9037 - rust_begin_unwind
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:475
   8:     0x55d0c92f0aad - core::panicking::panic_fmt::h519452995771b90d
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libcore/panicking.rs:69
   9:     0x55d0c8fd2812 - core::result::unwrap_failed::hd7ed6a47b3566980
  10:     0x55d0c9035c92 - librespot::player::Player::command::h5dc87f3a59fe4b6e
  11:     0x55d0c904612a - <librespot::spirc::SpircTask as futures::future::Future>::poll::hcdda3def9ee7ad9c
  12:     0x55d0c8fa205c - librespot::main::h9ec7a37d90b62374
  13:     0x55d0c92c1c7a - __rust_maybe_catch_panic
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libpanic_unwind/lib.rs:98
  14:     0x55d0c92b9a36 - std::rt::lang_start::h654cbbacaf320c39
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panicking.rs:434
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/panic.rs:351
                        at /build/rustc-SnYB1V/rustc-1.15.1+dfsg0/src/libstd/rt.rs:57
  15:     0x7ffbee25882f - __libc_start_main
  16:     0x55d0c8f90e58 - _start
  17:                0x0 - <unknown>
DEBUG:librespot::spirc: drop Spirc[0]
DEBUG:librespot::session: drop Session[0]
DEBUG:librespot::mercury: drop MercuryManager
DEBUG:librespot::metadata: drop MetadataManager
DEBUG:librespot::session: drop Dispatch

**Comment by plietar** [comment]
This is the same as #213 and #213 and should be fixed now

**Comment by pwielders** [comment]
It is working again. Thanks !
