### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by tatoosh** [plietar/librespot#216]
I got a problem bus the issue i searched here is already closed !? same problem by using the newest version (v20170709-aa86ebf)

INFO:librespot::session: Connecting to AP "lon3-accesspoint-a38.ap.spotify.com:4070"
thread 'main' panicked at 'Authentication failed', /home/travis/build/herrernst/librespot/target/arm-unknown-linux-gnueabihf/release/build/librespot-cbf31f11fa905ab0/out/lib.rs:365
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by tatoosh** [comment]
After a reboot it was working again!

**Comment by herrernst** [comment]
I am also getting "Authentication failed" since today, reboot doesn't help :(

**Comment by derWeihnachtsmann** [comment]
Same Problem. Just tested after your Reports came in. Ist was working Yesterday.. :/

**Comment by f69m** [comment]
Same issue, but when I kept trying it authenticated once. Maybe some APs work? But seems most don't.
Unfortunately can't quickly set a specific AP to verify, so just a guess.

**Comment by romqu** [comment]
You only have to change the string as the author has done it [here](https://github.com/plietar/librespot/commit/29d5f794d623a27b651513b3fca8dbc9b1ca7341)
Then just build it and it should work again.
