### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by gfro84** [plietar/librespot#219]
Anyone else having issues from the last 3 hrs? Either the streaming device tries to connect for 10s or it instantly dismissed the Spotify connect request. I've a 2 week old router been flawless up until tonight. Regards

**Comment by gfro84** [comment]
Or connects and plays no sound? Very erratic but always failing behaviour!

**Comment by gfro84** [comment]
And I should add, changed identifier from librespot to the Mac equivalent already.

**Comment by Bebowi** [comment]
Did you use #218 already?

**Comment by maxx** [comment]
I have been using it tonight without the above issues.  It seems fine for me.

**Comment by gfro84** [comment]
Perfect Bebowi (and thanks maxx) now working like a charm. Second time I've raised an issue that has already been resolved, apologies yet again.

Thanks
George
