### ISSUE TITLE
Still not working for me

### ISSUE THREAD

**Issue by lassos** [plietar/librespot#220]
Build today new version from git. Still getting:

```
INFO:librespot: librespot aa86ebf (2017-07-09). Built on 2017-07-15.
WARN:mdns::fsm: error sending packet Error { repr: Os { code: 1, message: "Operation not permitted" } }
INFO:librespot::session: Connecting to AP "lon6-accesspoint-a8.ap.spotify.com:4070"
INFO:librespot::session: Authenticated as "larsmultihome" !
INFO:librespot::session: Country: "DE"
thread '<unnamed>' panicked at 'assertion failed: s != null_mut()', src/audio_backend/pulseaudio.rs:39
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /checkout/src/libcore/result.rs:859
lars-multihome:/home/lars/system/librespot/target/release# librespot /home/lars/librespot/spotify_appkey.key --username larsmultihome --password --bitrate 320 --name multihome --backend pulseaudio
INFO:librespot: librespot aa86ebf (2017-07-09). Built on 2017-07-15.
WARN:mdns::fsm: error sending packet Error { repr: Os { code: 1, message: "Operation not permitted" } }
INFO:librespot::session: Connecting to AP "lon3-accesspoint-a60.ap.spotify.com:4070"
INFO:librespot::session: Authenticated as "larsmultihome" !
INFO:librespot::session: Country: "DE"
thread '<unnamed>' panicked at 'assertion failed: s != null_mut()', src/audio_backend/pulseaudio.rs:39
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /checkout/src/libcore/result.rs:859
lars-multihome:/home/lars/system/librespot/target/release#
```

**Comment by sashahilton00** [comment]
@lassos a couple of things:

1. You probably want to edit your password out of the comment.
2. What is spotify_appkey.key doing in there?

**Comment by lassos** [comment]
It seems to be that just  the mirror

INFO:librespot::session: Connecting to AP "lon2-accesspoint-a3.ap.spotify.com:4070"

works for me. Yes. I allready changed my password .-)

**Comment by noohgnas** [comment]
@sashahilton00

2. that key is for original spotify sdk.

**Comment by awiouy** [comment]
You are trying to use pulseaudio, and this yields your error. Do you really want to use pulseaudio? Is pulseaudio started?

**Comment by lassos** [comment]
No. Pulseaudio is not the reason. I got on every server authentication  failure except this:

INFO:librespot::session: Connecting to AP "lon2-accesspoint-a3.ap.spotify.com:4070"


> INFO:librespot: librespot aa86ebf (2017-07-09). Built on 2017-07-15.
WARN:mdns::fsm: error sending packet Error { repr: Os { code: 1, message: "Operation not permitted" } }
INFO:librespot::session: Connecting to AP "lon3-accesspoint-a5.ap.spotify.com:4070"
thread 'main' panicked at 'Authentication failed', /home/lars/system/librespot/target/release/build/librespot-94a18f1f95501f99/out/lib.rs:365
note: Run with `RUST_BACKTRACE=1` for a backtrace.

> INFO:librespot: librespot aa86ebf (2017-07-09). Built on 2017-07-15.
WARN:mdns::fsm: error sending packet Error { repr: Os { code: 1, message: "Operation not permitted" } }
INFO:librespot::session: Connecting to AP "lon6-accesspoint-a32.ap.spotify.com:4070"
thread 'main' panicked at 'Authentication failed', /home/lars/system/librespot/target/release/build/librespot-94a18f1f95501f99/out/lib.rs:365
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by sashahilton00** [comment]
That's probably because you aren't using librespot with the fix in #218...

**Comment by lassos** [comment]
Wit this fix it wokrs again.

https://github.com/plietar/librespot/pull/218

**Comment by Bebowi** [comment]
Can you give me an example how to use this fix? I know it works, but i think i'm doing something wrong
