### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by alepee** [plietar/librespot#223]
I reproduced it even with a fresh build.

```
$ sudo librespot --name HiFi --disable-audio-cache
INFO:librespot: librespot aa86ebf (2017-07-09). Built on 2017-07-16.
INFO:librespot::session: Connecting to AP "lon6-accesspoint-a33.ap.spotify.com:4070"
thread 'main' panicked at 'Authentication failed', /home/pi/librespot/target/release/build/librespot-83c123db35652385/out/lib.rs:365
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This happens even with direct login, cache enable and/or any other option. It will eventually work after a few tries.

For example `lon3-accesspoint-a2.ap.spotify.com:4070` works but not `lon6-accesspoint-a33.ap.spotify.com:4070`

Any guess?

PS: I don't have more details even with env var RUST_BACKTRACE set to 1

**Comment by sashahilton00** [comment]
You need to run `git pull`. Then run `cargo clean &&a cargo build`

**Comment by sashahilton00** [comment]
That should be `cargo clean && cargo build`

**Comment by alepee** [comment]
is this linked to `rand` update? https://github.com/plietar/librespot/compare/aa86ebf...master#diff-80398c5faae3c069e4e6aa2ed11b28c0R65

**Comment by alepee** [comment]
anyway it seems to work properly on every connection tentative. Thanks @sashahilton00

**Comment by sashahilton00** [comment]
@alepee nope, linked to the fact that Spotify requested that it identify as librespot and not as 'This is not the client you are looking for', so they blocked the latter. the git pull got the PR that fixed identification, and the cargo clean && build built it.
