### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: WireError("invalid value for enum: 13")', /checkout/src/libcore/result.rs:859

### ISSUE THREAD

**Issue by JKocerka** [plietar/librespot#228]
I get the following error when trying to run librespot with ALSA backend:
RUST_BACKTRACE=1 ./librespot --name SpotiPi --verbose

INFO:librespot: librespot 2259188 (2017-06-14). Built on 2017-06-26.
WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 97, message: "Address family not supported by protocol" } }
DEBUG:librespot::authentication::discovery: Post "/" {}
INFO:librespot::session: Connecting to AP "gew1-accesspoint-b-lmrw.ap.spotify.com:4070"
INFO:librespot::session: Authenticated as "********" !
DEBUG:librespot::session: new Session[0]
DEBUG:librespot::spirc: new Spirc[0]
DEBUG:librespot::mercury: new MercuryManager
DEBUG:librespot::session: Session[0] strong=3 weak=2
INFO:librespot::session: Country: "PL"
DEBUG:librespot::player: new Player[0]
INFO:librespot::audio_backend::alsa: Using alsa sink
DEBUG:librespot::mercury: subscribed uri=hm://remote/3/user/********/ count=0
DEBUG:librespot::spirc: kMessageTypeNotify "FRD-L09" da2e94c28e66cb7d70b33fd929ea19d72c4e02d1 1 1501186500996
DEBUG:librespot::spirc: kMessageTypeLoad "FRD-L09" da2e94c28e66cb7d70b33fd929ea19d72c4e02d1 2 0
DEBUG:librespot::player: command=Load(SpotifyId(u128 { high: 16505002772753303400, low: 9692160635951389779 }), false, 673)
DEBUG:librespot::metadata: new MetadataManager
DEBUG:librespot::spirc: kMessageTypeNotify "FRD-L09" da2e94c28e66cb7d70b33fd929ea19d72c4e02d1 15 1501186500996
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: WireError("invalid value for enum: 13")', /checkout/src/libcore/result.rs:859
stack backtrace:
DEBUG:librespot::spirc: kMessageTypeNotify "SpotiPi" 70df4a9775279d6f031b370a3c7c8c8de0465c32 2 1501186634551
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  11: librespot::player::PlayerInternal::load_track
  12: librespot::player::PlayerInternal::run
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  15: <F as alloc::boxed::FnBox<A>>::call_box
  16: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
DEBUG:librespot::player: drop Player[0]
DEBUG:librespot::spirc: kMessageTypePlay "FRD-L09" da2e94c28e66cb7d70b33fd929ea19d72c4e02d1 3 0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: librespot::player::Player::command
  11: <librespot::spirc::SpircTask as futures::future::Future>::poll
  12: librespot::main
  13: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  15: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  16: __libc_start_main
DEBUG:librespot::spirc: drop Spirc[0]
DEBUG:librespot::session: drop Session[0]
DEBUG:librespot::mercury: drop MercuryManager
DEBUG:librespot::metadata: drop MetadataManager
DEBUG:librespot::session: drop Dispatch

Sometimes it happens when I connect to librespot, sometimes when I'm trying to play a song. RUST_BACKTRACE=1 ./librespot --name SpotiPi --verbose
INFO:librespot: librespot 2259188 (2017-06-14). Built on 2017-06-26.
WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 97, message: "Address family not supported by protocol" } }
DEBUG:librespot::authentication::discovery: Post "/" {}
INFO:librespot::session: Connecting to AP "gew1-accesspoint-b-lmrw.ap.spotify.com:4070"
INFO:librespot::session: Authenticated as "rudyjerz" !
DEBUG:librespot::session: new Session[0]
DEBUG:librespot::spirc: new Spirc[0]
DEBUG:librespot::mercury: new MercuryManager
DEBUG:librespot::session: Session[0] strong=3 weak=2
INFO:librespot::session: Country: "PL"
DEBUG:librespot::player: new Player[0]
INFO:librespot::audio_backend::alsa: Using alsa sink
DEBUG:librespot::mercury: subscribed uri=hm://remote/3/user/rudyjerz/ count=0
DEBUG:librespot::spirc: kMessageTypeNotify "FRD-L09" da2e94c28e66cb7d70b33fd929ea19d72c4e02d1 1 1501186500996
DEBUG:librespot::spirc: kMessageTypeLoad "FRD-L09" da2e94c28e66cb7d70b33fd929ea19d72c4e02d1 2 0
DEBUG:librespot::player: command=Load(SpotifyId(u128 { high: 16505002772753303400, low: 9692160635951389779 }), false, 673)
DEBUG:librespot::metadata: new MetadataManager
DEBUG:librespot::spirc: kMessageTypeNotify "FRD-L09" da2e94c28e66cb7d70b33fd929ea19d72c4e02d1 15 1501186500996
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: WireError("invalid value for enum: 13")', /checkout/src/libcore/result.rs:859
stack backtrace:
DEBUG:librespot::spirc: kMessageTypeNotify "SpotiPi" 70df4a9775279d6f031b370a3c7c8c8de0465c32 2 1501186634551
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  11: librespot::player::PlayerInternal::load_track
  12: librespot::player::PlayerInternal::run
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  15: <F as alloc::boxed::FnBox<A>>::call_box
  16: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
DEBUG:librespot::player: drop Player[0]
DEBUG:librespot::spirc: kMessageTypePlay "FRD-L09" da2e94c28e66cb7d70b33fd929ea19d72c4e02d1 3 0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: librespot::player::Player::command
  11: <librespot::spirc::SpircTask as futures::future::Future>::poll
  12: librespot::main
  13: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  15: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  16: __libc_start_main
DEBUG:librespot::spirc: drop Spirc[0]
DEBUG:librespot::session: drop Session[0]
DEBUG:librespot::mercury: drop MercuryManager
DEBUG:librespot::metadata: drop MetadataManager
DEBUG:librespot::session: drop Dispatch

It happens all the time and I'm not able to play any song.

**Comment by kingosticks** [comment]
You dont appear to be running the latest code. The first thing you should do, before posting an issue, is run the latest code.

**Comment by JKocerka** [comment]
You are right. My bad. 
I build it the previous day, but I build the debug version and run the release.

**Comment by kingosticks** [comment]
Easy mistake I've done many times! No worries.
