### ISSUE TITLE
compilation fails on x86

### ISSUE THREAD

**Issue by balbuze** [plietar/librespot#233]
Hi!
I cross  compiled last version for raspberry ok.
Now I can't compil it for x86
It starts and after several minutes it fails when compiling unicode-bidi
the command I use :  cargo build --release --no-default-features --features alsa-backend

> 

`  Compiling mime v0.3.2
   Compiling unicode-bidi v0.3.4
error: struct field shorthands are unstable (see issue #37340)
   --> /home/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/explicit.rs:180:32
    |
180 |         self.vec.push(Status { level, status });
    |                                ^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/explicit.rs:180:39
    |
180 |         self.vec.push(Status { level, status });
    |                                       ^^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:226:13
    |
226 |             text,
    |             ^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:227:13
    |
227 |             original_classes,
    |             ^^^^^^^^^^^^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:228:13
    |
228 |             paragraphs,
    |             ^^^^^^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:303:13
    |
303 |             text,
    |             ^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:304:13
    |
304 |             original_classes,
    |             ^^^^^^^^^^^^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:305:13
    |
305 |             paragraphs,
    |             ^^^^^^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:306:13
    |
306 |             levels,
    |             ^^^^^^

error: aborting due to 9 previous errors

error: Could not compile `unicode-bidi`.
Build failed, waiting for other jobs to finish...
`

**Comment by plietar** [comment]
You need to upgrade your rust compiler. One of the dependencies has started requiring 1.17.0.

**Comment by balbuze** [comment]
ok thanks a lot

**Comment by balbuze** [comment]
ok compilation done! we can close it now
