### ISSUE TITLE
Close stream on stop

### ISSUE THREAD

**Issue by herrernst** [plietar/librespot#26]
I've noticed that the audio device keeps staying active even after playback is stopped for example by changing the "speaker" back to the playing Spotify app. I suspect this is because the stream stays open because `drop(stream)` is never reached.
I've tried refactoring `stream` to an optional mutable like `decoder` and set `stream = None` on stop in my branch at https://github.com/herrernst/librespot/tree/close-stream-on-stop.
Unfortunately, this most of the time leads to a segmentation fault, see [lldb backtrace](http://pastebin.com/qDD1bGR7), [gdb backtrace](http://pastebin.com/9zjM7P2N).
I am very new to Rust and also don't fully understand player.rs yet.
Thanks for your help! I will stop annoying you for now ;)

**Comment by joerg-krause** [comment]
Any news about this?

**Comment by herrernst** [comment]
It does work quite well for me after this error was fixed: https://github.com/mvdnes/portaudio-rs/pull/12
So no segmentation faults anymore.
But I've not adopted the code to the multiple backend refactoring done a while ago yet.

**Comment by joerg-krause** [comment]
I wonder which part of code is actually responsible for closing the session, so I can adopt the code to the multiple backend (where `stream` is replaced by `sink`).

**Comment by herrernst** [comment]
It's just setting `stream` to `None`: https://github.com/herrernst/librespot/commit/68b11dc683a2622d6cd5501641ca398893d8f7d7#diff-ea99e5f26c9c71eef88e4a8fcd5f6fceR180
The destructor `drop` then makes portaudio close the stream (and free the audio device): https://github.com/mvdnes/portaudio-rs/blob/master/src/stream.rs#L494
It probably could/should be changed in the portaudio backend, `stream` should be dropped in the `stop()` method of the sink: https://github.com/plietar/librespot/blob/master/src/audio_backend/portaudio.rs#L26

**Comment by joerg-krause** [comment]
Unfortunately, setting `stream = None` does not work with the multiple backend implementation:

```
error: mismatched types [E0308]
note: expected type `Box<audio_backend::Sink + 'static>`
note:    found type `std::option::Option<_>`
```

Sadly, I have no experience with Rust.

**Comment by herrernst** [comment]
I think I somehow got around it, try this: https://github.com/herrernst/librespot/tree/close-stream-on-stop2

**Comment by joerg-krause** [comment]
@herrernst  Many thanks for this! I adopted it to the alsa backend: https://github.com/joerg-krause/librespot/commit/ea0fe73b6b77d13ab85269ba3f0f4fa159784bce.

Now the stream is closed when playback is stopped :smile:
