### ISSUE TITLE
Many user with spotify family

### ISSUE THREAD

**Issue by nino59case** [plietar/librespot#271]
Hello, first of all thank you for this extension.
I tested it in premium mode and it works perfectly but now I have a family account.
Since this change the autodiscover mode no longer works, and you must use its username and password.
Outside we are many at home from where the interest of the family account and it is really not easy to pass from one user to another.
Would it be possible to select an account in a list for example, to simply share the same kodi instance?

Nino59cas

**Comment by mrwsl** [comment]
Can't confirm this issue. I'm using librespot with my family account.

**Comment by maxx** [comment]
I also cannot confirm. We use a family plan with two accounts and it switches over fine. I’m runninng a July 2017 build (from justvafter client is shenanigans)

**Comment by nino59case** [comment]
Thank you for your answers,
I check again and come back to you

Nino59cas

**Comment by cortegedusage** [comment]
Are you sure you don't start librespot with credentials.

Op 11 jan. 2018 4:50 p.m. schreef "nino59case" <notifications@github.com>:

**Comment by herrernst** [comment]
Maybe it makes a difference if you start librespot with cache directory (`-c, --cache CACHE`) or without. Because if you use a cache directory, a credentionals.json is saved there with a login token.

**Comment by nino59case** [comment]
hlelo,
I redid the tests yesterday and this time it worked perfectly with all users in discovery mode.
I did not change anything yet.
For info I use up to date kodi libreelec with the latest version of librespot.
I wonder if the problem did not come from spotify, I also had problems with authenfication on Android following the update to the latest version.
Thank you for your feedback and I hope I do not encounter any problem
Nino59cas
