### ISSUE TITLE
Librespot crashed when trying to start any song 9.0.1.109

### ISSUE THREAD

**Issue by Jeycop** [plietar/librespot#280]
Hi there,
Sry for using "Leia Alpha Version" of Kodi, but would be really nice to have spotify on it ;-)
I pressed on Librespot as device in Spotify settings, then it suddenly dissapears from list.
Pass and name are correctly filled (it is logged into spotify -> I see it on device list)

service.librespot v9.0.1.109 installed on Libreelec 8.90.4
DEBUG: CAddonSettings[service.librespot]: loading setting definitions
DEBUG: CAddonSettings[service.librespot]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[service.librespot]: loading setting values
WARNING: CAddonSettings[service.librespot]: failed to load value "" for setting ls_o

Big thanks for your work here!! Sry for my english.

**Comment by awiouy** [comment]
Please report Librespot for LibreELEC bugs at the [LibreELEC forum](https://forum.libreelec.tv/thread/8438-librespot-addon/).

For information:
- this github repository is unmaintained
- addon revision 109 is outdated (current is 110)
- I do not know addon release 9.0.1.109 and LibreELEC version 8.90.4 (community builds?)

In any case, report your problem at the forum, we will try to fix it.

**Comment by Jeycop** [comment]
Really big Thanks for this information and your really fast answer!!
I will try the newest Version 110. 
Thank you.
Yeah, Community build
