### ISSUE TITLE
librespot crashes when connecting from both android and PC

### ISSUE THREAD

**Issue by okrantz** [plietar/librespot#281]
Hello

This started happening in the last days when I try to connect from my phone or PC - using it on a Vero 4K running OSMC.

`osmc@osmc-Ichabod:~$ RUST_BACKTRACE=1 librespot --name Kodi --backend alsa --bitrate 320  --username XXXX --password XXXX --device plughw:CARD=II,DEV=0
INFO:librespot: librespot (raspotify) 5f21c25 (2018-01-28). Built on 2018-01-29. Build ID: ol042t2I
WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-blgr.ap.spotify.com:4070"
INFO:librespot_core::session: Authenticated as "okrantz" !
INFO:librespot::audio_backend::alsa: Using alsa sink
INFO:librespot_core::session: Country: "SE"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: __libc_start_main
`
Is there anything else you need to know? 

Except for this I want to thank you for a great application - fantastic!
/okrantz

**Comment by okrantz** [comment]
Don't know what happened - what I wanted to paste was <unknown> on 0: to 15: .

**Comment by ComlOnline** [comment]
Hey @okrantz , 

Basically Spotify changed something, see [here](https://github.com/librespot-org/librespot/issues/181).

**Comment by okrantz** [comment]
Thank you! Fixed it.

/okrantz
