### ISSUE TITLE
Add support for setting audio output device name

### ISSUE THREAD

**Issue by joerg-krause** [plietar/librespot#32]
Currently, librespot uses the default audio output device offered by portaudio. How about adding a command line option which allows the user to use a different audio device, e.g.:

``` sh
librespot [..] -d "dmix"
```

**Comment by markdegrootnl** [comment]
Would really like this

**Comment by plietar** [comment]
Implemented in 1396f97

**Comment by joerg-krause** [comment]
Thanks! Would be great if you can document this...
