### ISSUE TITLE
Pure rust mDNS/Zeroconf implementation

### ISSUE THREAD

**Issue by plietar** [plietar/librespot#33]
librespot currently depends on dns-sd for service registration. This makes build quite painful / impossible on windows and is currently optional for this reason.

A pure rust implementation of mDNS and Zeroconf would fix this by removing this dependency.

**Comment by joerg-krause** [comment]
On many Linux system avahi is available. Why not use a Rust binding to avahi?

**Comment by plietar** [comment]
Avahi provides a dns-sd compatibility layer which seems to work fine (The Debian package name is `libavahi-compat-libdnssd-dev`)
A native Avahi binding would be nice but not a priority for now.

The main problem is windows, and small embedded Linux devices on which running Avahi may not be desirable.

**Comment by joerg-krause** [comment]
> ... and small embedded Linux devices on which running Avahi may not be desirable.

Why not? Is it because of the size? I am using the avahi-client library on an ARMv5 device for shairport-sync:

```
   text    data     bss     dec     hex filename
 178734    1736      32  180502   2c116 hbm10/output/target/usr/lib/libavahi-core.so.7.0.2
  51072    1056      28   52156    cbbc hbm10/output/target/usr/lib/libavahi-client.so.3.2.9
  38069     868      68   39005    985d hbm10/output/target/usr/lib/libavahi-common.so.3.5.3
  29864    1428     180   31472    7af0 hbm10/output/target/usr/lib/libavahi-gobject.so.0.0.4
   7611     412      48    8071    1f87 hbm10/output/target/usr/lib/libavahi-glib.so.1.0.2
```

I most confess I am not sure if all library files are necessary...

**Comment by alexchandel** [comment]
Avahi provides a compatibility layer with Bonjour. But Bonjour also works on Windows, so it could be used on all three. It's usually discouraged to do your own DNS resolution & registration over the system's...

**Comment by plietar** [comment]
@joerg-krause using the avahi-client library requires the avahi daemon, which is fairly overkill if librespot is the only service requiring it.
It also makes cross compiling harder. The only two dependencies which cannot be built by cargo currently are bonjour (or avahi's compatibility layer) and portaudio. I'm working on removing the latter, so removing bonjour would be the last step to an easy cross compilation.
An alternative would be to have cargo and the GCC crate build avahi-client from source.

@alexchandel I think someone tried a while back to get librespot to link to bonjour on windows but failed. I don't have a windows box myself so I can't try.
Multiple mDNS responders on a single machine is permitted by the RFC, just not recommended. In my experience I've found it to work without any trouble

**Comment by joerg-krause** [comment]
@plietar With avahi version 0.6.32 it's possible to build the avahi-client without the daemon: https://github.com/lathiat/avahi/commit/54086a11033194e629b6ad7039bcb4fb1628e052

I would argue that avahi is available on most Linux distributions, and it's out for years now. And cross-compiling avahi shouldn't be that hard.

**Comment by alexchandel** [comment]
@plietar Be sure to use the latest version of bonjour for windows. Since bonjour/avahi-compat is essentially a missing OS component (mDNS/SD-SD), why not just install it?

@joerg-krause Avahi does not work on OS X or Windows, as its implementation uses both posix and linux-specific glibc symbols, so it is very hard (i.e. impossible) to cross-compile it, since OS X isn't linux and Windows has infinitesimal posix support. On the other hand, the bonjour API is callable on all three platforms.

**Comment by sashahilton00** [comment]
Personally I agree with alex here. OSX comes with DNS-SD, Windows can install the Bonjour package, and this can be done silently and installation could even be included in the librespot compile script. Linux has avahi. Between them, they cover pretty much every system librespot will run on, with the added benefit that they are tried and trusted for years, as opposed to another rust component that needs to be maintained.

**Comment by plietar** [comment]
> installation could even be included in the librespot compile script

Definitely not.

Has anyone been able to build librespot with discovery on windows ? Not that I'm aware of. If so please contribute building instructions.
I also want cross compilation to be as easy as `cargo build --target=arm-unknown-linux-gnueabihf`. But today it isn't because of the avahi and portaudio dependencies.

If someone can solve these problems without including a zeroconf implementation in librespot I'd be happy to merge it. In the meantime, I still consider this an issue (albeit of low priority, since discovery isn't such a critical feature, and can be disabled).

**Comment by herrernst** [comment]
By using Bonjour on Windows, do you mean Apple's Bonjour from here? https://support.apple.com/kb/DL999
That may be a dead end, because the last update of it is from 2010. I think that was a port of mDNSResponder responder to Windows, which has been replaced since OS 10.10 with discoveryd.
Update: I see it is also integrated into iTunes for Windows: http://superuser.com/questions/491747/how-can-i-resolve-local-addresses-in-windows
Update 2: At least it's open source, and also seems to be still maintained: http://www.opensource.apple.com/source/mDNSResponder/

**Comment by joerg-krause** [comment]
@alexchandel I thought in terms of different CPU architectures (ARM, Mips, ...) when speaking about cross-compiling, but you're right: building on Linux for OS X or Windows is cross-compiling, too.

mDNSResponder is available for Posix, Windows and OS X, although I never tried to use it.

**Comment by alexchandel** [comment]
lol I thought in the complementary terms. OS X is Posix, but not Linux.

@herrernst `discoveryd` does not replace `mDNSResponder`. It briefly did, but was scrapped immediately and merged back. mDNSResponder is the standard and is actively developed, though it's pretty stable. The link on their website is old for some reason, and might merit a bug report. The build that ships with iTunes for windows is updated regularly, and it's not hard to extract its `msi` from the iTunes `msi`.

I've never tried to build it from source before, but I'd be interested in how it goes.

**Comment by herrernst** [comment]
@alexchandel You're right, `mDNSResponder` still runs on 10.11, and it's easy to extract it from the iTunes msi for Windows.

**Comment by alexchandel** [comment]
@herrernst I'm not sure whether you'd prefer bundling/requiring that be installed on windows, or compiling it yourself. Given the Bonjour license however, there's nothing wrong with just hosting it online somewhere.

**Comment by delacor** [comment]
I have problems seeing the librespot deamon in Spotify in discovery mode because dns-sd is not enabled. I've installed avahi and configured some things(domainname.etc.) in the config but still running in this Error.. I'm sure I missed something but right now I don't know where to ask (plietar's twitter seems not to match the github profile) and hope for a quick hint in here. Warm regards!

**Comment by sashahilton00** [comment]
@Delacor head over to the gitter chatroom and ask your question prefixed with @plietar that is probably the best way to reach him. Or he might respond here...

Gitter chatroom: https://gitter.im/sashahilton00/spotify-connect-resources
