### ISSUE TITLE
move from portaudio to libao

### ISSUE THREAD

**Issue by psych0d0g** [plietar/librespot#35]
More leightweight, support for nearly all audio subsystems, crossplatform and more recently developed library.

https://xiph.org/ao/

**Comment by plietar** [comment]
I'm OK with the idea but it would require rust libao bindings.
The two I've found are fairly out of date, and don't build on latest rust
https://github.com/tari/rust-ao
https://github.com/pcwalton/rust-ao

They could be used as a starting point (the first one in particular)

**Comment by psych0d0g** [comment]
that was an easy fix, https://github.com/tari/rust-ao/pull/2

**Comment by psych0d0g** [comment]
example c code for libao:

https://www.xiph.org/ao/doc/ao_example.c

documentation and example for bindings: 

http://android.crystalnet.org/ao/

**Comment by CoDEmanX** [comment]
Any idea how well libao would compile on Windows? portaudio is quite a hassle, and it's way better to use a pre-compiled DLL and copy it next to the target binary. Would be much nicer to compile the required bits directly into the executable, but only if there are not tons of dependencies.

**Comment by psych0d0g** [comment]
there seems to be a vcproj fork: https://github.com/manushanga/libao-win32
but nethertheless it should compile fine on windows.
i might setup a mingw compile and try that

**Comment by plietar** [comment]
Haha, thanks.
I'll look into it.
Since libao is so small, a nice thing to do would be making a ao-sys crate and include the source verbatim, like the [ogg-sys](https://github.com/tomaka/ogg-sys) crate does as a fallback if not found using pkg-config. That would simplify build, especially on windows and cross compiling

**Comment by psych0d0g** [comment]
and libao has only optional dependencies for X Window System, ALSA-1.0.28, and PulseAudio-5.0
nothing that prevents compiling when its not available

**Comment by plietar** [comment]
Meh, I've just realized libao is GPL2. Unfortunately that's going to be a no go
