### ISSUE TITLE
Volume control - default volume low (50%?)

### ISSUE THREAD

**Issue by smoltron** [plietar/librespot#44]
librespot is working fine in my Raspberry now. Any spotify client cannot however control the volume of librespot. My alsa setting is now 100% volume, but the level is quite low and i think it is on the default spotify volume which may be 50%. For a high-end application 100% would be much better. Is there any way to control librespot volume or make the default 100%?

**Comment by plietar** [comment]
You can control the volume remotely from the Spotify clients.
The volume is implemented entirely in software simply by applying a factor to the samples (ie it won't change the alsa volume)
I've changed it to default to 100% : 526c547
