### ISSUE TITLE
Building with stable rust

### ISSUE THREAD

**Issue by plietar** [plietar/librespot#48]
Since librespot was started rust has stabilized a lot of stuff. As a result where lots of unstable features were required before, only `zero_one`, `iter_arith`, and `plugin` are needed now.

The first two are trivial to work around.
The last one not so much. The two plugins used are `json_macros`, which could easily be avoided, and `protobuf_macros` which is used a lot and would be a pain to get rid, both in terms of work and readability.

[syntex](https://github.com/serde-rs/syntex) would be a potential solution to this.

**Comment by plietar** [comment]
Building on rust stable now works (d27c4ca).
I'm keeping this open until I update the README.

**Comment by herrernst** [comment]
This is great news! There is one last gotcha when building with discovery: https://github.com/plietar/rust-dns-sd/pull/2
Thank you!

**Comment by plietar** [comment]
Oops, good catch thanks.
I probably need to update Cargo.lock as well, I'll do that when I get back this evening.

**Comment by plietar** [comment]
README has been updated, with instructions on how to build without syntex.
Travis also builds using stable, beta and nightly, making sure stable support doesn't break unexpectedly.
