### ISSUE TITLE
Error: assertion "_dbus_check_is_valid_utf8 (*string_p)" failed in file ../../dbus/dbus-message.c

### ISSUE THREAD

**Issue by b-per** [plietar/librespot#49]
When running the Spotify Connect example `target/debug/librespot --appkey spotify_appkey.key --cache tmp --name pi` the following error appears

```
process 17124: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_check_is_valid_utf8 (*string_p)" failed in file ../../dbus/dbus-message.c line 2676.
This is normally a bug in some application using the D-Bus library.
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: DNSError(NoMemory)', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The following errors are showing when I activate the backtrace

```
   1: 0x54f1a433 - sys::backtrace::tracing::imp::write::h12167fd87c4444bfCwu
   2: 0x54f1ce17 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43431
   3: 0x54f1c99b - panicking::default_handler::h9f8ceb45c392442dd5y
   4: 0x54f0aa6f - sys_common::unwind::begin_unwind_inner::hf5f65b9eced8cd83rlt
   5: 0x54f0afb3 - sys_common::unwind::begin_unwind_fmt::h8fbe76036c0b1b80xkt
   6: 0x54f199fb - rust_begin_unwind
   7: 0x54f24f4f - panicking::panic_fmt::hf5513279aa3d2ea26YL
   8: 0x54c3379f - result::unwrap_failed::h11053035362580410660
                at ../src/libcore/macros.rs:29
   9: 0x54c33597 - result::Result<T, E>::unwrap::h16659752087029109074
                at ../src/libcore/result.rs:687
  10: 0x54c15733 - discovery::DiscoveryManager::run::h86f7924c19979c7fL2b
                at src/discovery.rs:121
  11: 0x54b4442b - main::h4deaf41955222e3dXba
                at src/main.rs:96
  12: 0x54f1c56b - sys_common::unwind::try::try_fn::h13484918573325342335
  13: 0x54f19993 - __rust_try
  14: 0x54f19993 - __rust_try
...
  100: 0x54f19993 - __rust_try
```

I have compiled librespot on my Raspberry Pi 2 using the latest Rust nightly and the latest version of librespot

**Comment by b-per** [comment]
Quick update. When compiling librespot without the flag `--features discovery` I don't have the problem and librespot works correctly.

**Comment by herrernst** [comment]
Maybe it's about no more memory on your pi ("DNSError(NoMemory)"). You should use the release build on slower devices like Raspberry Pi 2 (`--release`), also see https://github.com/plietar/librespot/issues/53. Maybe you also need to stop other services on your pi (although librespot doesn't need much memory).

**Comment by b-per** [comment]
Same thing with the `--release` flag. I can run librespot specifying my user and password but the discovery crashes with the same error as before: `DNSError(NoMemory)`

**Comment by herrernst** [comment]
Another blind guess from the error message would be that your computer's name has some non-ascii characters in it which fail a conversion to utf8 (what's your output of `hostname`). Or maybe your Spotify username has some non-ascii chars?

**Comment by plietar** [comment]
The username shouldn't matter, it isn't involved in the mdns advertisement.
On the other hand, the hostname could be the cause.

If you run the following, what do you get ?

```
avahi-publish -s TestService _http._tcp 1234
```

**Comment by b-per** [comment]
I had to install `avahi-utils`to get the command `avahi-publish` working but when I did it, here is the outcome of the command:

```
osmc@osmc:~/dev/spotify/librespot$ avahi-publish -s TestService _http._tcp 1234
Established under name 'TestService'
```

And my hostname is osmc

**Comment by plietar** [comment]
@camfrout Could you try again with the latest master ?
It could very much have been the same bug as plietar/rust-dns-sd#3, which was just fixed.
Thanks

**Comment by b-per** [comment]
Different issue now, I recompiled librespot to take in account v 0.1.3 of rust-dns-sd but when I run the program  in discovery mode I have the following: `WARNING: dns-sd is not enabled. Service will probably not be visible` and nothing more happens.

**Comment by sashahilton00** [comment]
At the risk of sounding like a condescending a**, did you compile with --features discovery?

**Comment by b-per** [comment]
Yes, but using the --release tag as well: `cargo build --release --features discovery`

**Comment by herrernst** [comment]
You're sure you running the right binary? Maybe try `cargo clean` before.

**Comment by sashahilton00** [comment]
Try rebasing and rebuilding? Sounds like there has been something messy
happening with dns-sd in the cache or something.

On Fri, Mar 11, 2016 at 2:26 p.m., herrernst notifications@github.com wrote:
You're sure you running the right binary? Maybe try cargo clean before.

—
Reply to this email directly or view it on GitHub
[https://github.com/plietar/librespot/issues/49#issuecomment-195387193] .[https://github.com/notifications/beacon/AD_dEtq3bJSoeCNgt-AxO0JxfA2Z7Daxks5psXuQgaJpZM4HcyxF.gif]

**Comment by b-per** [comment]
The issue was indeed from my side. I ran an old bash script I used to test the discovery feature but the executable listed in my script was still the debug one.

It is working now, thanks everyone, I am closing the issue.
