### ISSUE TITLE
Doesn't start playing anymore

### ISSUE THREAD

**Issue by herrernst** [plietar/librespot#50]
With the changes in 3ccb2e2a1035192889033b2fe7f5626787798261, librespot doesn't start playing anymore (iOS just shows "connecting ...").

**Comment by plietar** [comment]
I can reproduce this. It seems to be a deadlock between the Player and the SpircManager.
Working on it ...

**Comment by plietar** [comment]
Fixed by c700315.

**Comment by herrernst** [comment]
👍
