### ISSUE TITLE
Constant underflows in Raspberry 2

### ISSUE THREAD

**Issue by smoltron** [plietar/librespot#53]
I just compiled the most recent version to Raspberry Pi 2.

Streaming almost works. The connection is created and streaming starts, but then there are underflows every other second. Later the frequency of underflows is slower, but the still come. The CPU is > 90% idle and my network is fast enough. The underflows kill the music with stuttering and gaps.

When starting, librespot complains about missing jack server. Is that needed?

**Comment by jkgeyti** [comment]
A little unrelated, but can I ask how you compiled for the raspberry pi? I got errors with `cargo build --target=arm-unknown-linux-gnueabihf`.

**Comment by smoltron** [comment]
I compiled in Raspberry PI 2 with the binaries from here: https://github.com/warricksothr/RustBuild
Raspberry 1 cannot compile librespot probably because of too little memory for protobuf macros compilation. Raspberry 2 compiles fine.

**Comment by smoltron** [comment]
And, for comparison, the chrooted installation of spotify-connect-web works without major issues.

**Comment by plietar** [comment]
Is this a debug or a release build ?

**Comment by smoltron** [comment]
I did `git pull`, compiled with `cargo build` and ran as instructed `target/debug/librespot --appkey APPKEY --username USERNAME --cache CACHEDIR --name DEVICENAME`

**Comment by plietar** [comment]
If you use `cargo build --release`, and then call use the `target/release/librespot` does it work any better ?
Compile time may be significantly larger if building directly on the pi

**Comment by smoltron** [comment]
Thanks! I will try that tonight at home.

**Comment by smoltron** [comment]
Excellent! The release build does not produce any underflows.

**Comment by plietar** [comment]
Thanks, good to know.
I've updated the readme instructions accordingly (ace5d09).
