### ISSUE TITLE
Support for Tremor

### ISSUE THREAD

**Issue by joerg-krause** [plietar/librespot#58]
libvorbis is an ogg decoder library targeted for architectures with floating-point support. Tremor is an alternative decoder implementation that provides an integer-only implementation for soft-float devices.

The Tremor lib is not a drop-in replacement for libvorbis/libvorbisfile (the original libs have a source API that uses float arguments) but it is very similar.

As there does not exists any Rust bindings for Tremor this has to be implemented first.

**Comment by plietar** [comment]
Thanks for the suggestion.
The bindings were almost identical to the libvorbisfile ones, so that was a fairly easy one.

You can build librespot with Tremor using the following command :

```
cargo build --release --features with-tremor
```

Let me know how that performs compared to the libvorbis build.

@psych0d0g this may improve the performance on MIPS as well, could you give it a shot please.

**Comment by joerg-krause** [comment]
Wow, many thanks for this!

Playback is much better now, but only for a while. CPU usage increases from about 40% to 90% after about 30 seconds. Furthermore, RAM decreases slowly but permanently.

**Comment by joerg-krause** [comment]
My bad, I was using `/dev/null` as cache directory, which librespot does not really like. CPU usage is about 80 % now, and RAM usage does not increase anymore.

**Comment by michaelherger** [comment]
@joerg-krause - is Tremor support still working for you? Have you been able to cross-compile this? Trying to do so on a Pi3 (cargo build --no-default-features --features with-tremor --target arm-unknown-linux-musleabi) I'm getting the following:

>   = note: /usr/bin/ld: error: /home/pi/git/librespot/target/arm-unknown-linux-musleabi/debug/deps/libtremor_sys-330fbfde9907f172.rlib(vorbisfile.o) uses VFP register arguments, /home/pi/git/librespot/target/arm-unknown-linux-musleabi/debug/deps/librespot-04d4255f3ee4ecdd does not
