### ISSUE TITLE
fedora dependencies - correction to readme

### ISSUE THREAD

**Issue by arigit** [plietar/librespot#68]
The following is missing in the fedora dependencies list

sudo dnf install protobuf-devel

**Comment by plietar** [comment]
Are you sure this is needed ? The README already mentions libprotoc-dev which is enough AFAIK.

**Comment by arigit** [comment]
Yes 100% sure.

Actually that's the problem, in fedora there is no libprotoc-dev package. The package name is protobuf-devel.

**Comment by herrernst** [comment]
AFAIK all *-dev packages on Debian are named *-devel on Fedora/RedHat.

**Comment by plietar** [comment]
Fixed. Thanks for the report
