### ISSUE TITLE
OSX: rust-gmp links to gmp but library path is missing

### ISSUE THREAD

**Issue by torarnv** [plietar/librespot#7]
[plietar/rust-gmp](https://github.com/plietar/rust-gmp) links to `libgmp`, which is eg. available through homebrew (as `gmp`), but `/usr/local/lib` is not in the library paths. 

Other packages add library paths using `pkg-config` which point directly into the Cellar, but gmp doesn't ship the required pkg-config files. A workaround is to add a `.cargo/config` file with eg:

```
[target.x86_64-apple-darwin.gmp]
rustc-link-search = ["/usr/local/Cellar/gmp/6.0.0a/lib"]
```

**Comment by plietar** [comment]
I've removed the dependency on GMP by using rust's num crate.
It is awfully slow in debug mode, but simplifies maintenance a lot.
