### ISSUE TITLE
Compile fails (in dns-sd) with misleading error messages

### ISSUE THREAD

**Issue by mfeif** [plietar/librespot#70]
I'm compiling librespot from the marcust fork (I want the pulse audio stuff) on x86_64 for arm-unknown-linux-gnueabihf. (shooting for rpi1)

```
$ rustc -V
rustc 1.8.0-beta.2 (2879d940a 2016-03-22)
```

My command is this:
`RUST_BACKTRACE=1; cargo build --release --features "discovery pulseaudio-backend" --target arm-unknown-linux-gnueabihf --verbose`

```
   Compiling dns-sd v0.1.3
     Running `/home/mjf/librespot/target/release/build/dns-sd-b5325db701df81ec/build-script-build`
Build failed, waiting for other jobs to finish...
failed to run custom build command for `dns-sd v0.1.3`
Process didn't exit successfully: `/home/mjf/librespot/target/release/build/dns-sd-b5325db701df81ec/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.

mjf@dude:~/librespot$ echo $RUST_BACKTRACE $PKG_CONFIG_ALLOW_CROSS
1 1
```

So both of those env vars are set, but that's as much output as I can gather.

Thanks!

**Comment by marcust** [comment]
The pulse audio stuff is already merged to master, but anyway.

I never really understood the Rust cross stuff. Is RPi1 Raspbian Jessy armhf as well? 

Otherwise because it happens with the dns-sd stuff, are you sure that you have all of the build dependencies installed? 
I usually have 

`build-essential, libprotoc-dev, libpulse-dev, portaudio19-dev, libavahi-compat-libdnssd-dev` 

installed in order to build, but I don't cross compile.

**Comment by mfeif** [comment]
I do have all of that stuff, and I have successfully built for native (and it's working AMAZINGLY WELL, thank you... much more reliable than my chromecast audio sink).

I don't understand the cross stuff either; it's astoundingly complicated.

I'm definitely targeting raspbian, Jessie, raspberry pi v1 (so, arm6, not arm7). The cpu variations get complicated quickly, but it _seems_ like "arm-unknown-linux-gnueabihf" is the relevant target.

Thanks for letting me know about the pulse merge; it's a little hard for me to follow the network graph.

Is your .deb packaging branch pretty solid? I could just go there... :-)

**Comment by marcust** [comment]
Well, I basically just build very basic packages for personal use, but I'm not cross compiling but always building on that platform. And I started to always build my own logging branch, which has some enhancements over the stuff that is in master to the PulseAudio output as well.

I still don't know if Pi2 packages actually work on the Pi1, but you can give the packages from http://dropbox.thiesen.berlin a try.

**Comment by mfeif** [comment]
I'd be interested in nicer (packaged) versions for my personal use on my x86_64 platform (my main use; this rpi stuff is because I was so encouraged by the other)...

Thanks for sharing all of that! I'll definitely try installing them. Maybe if I can get the packages to compile for rpi, I can share back.

To be honest, I've had 3 or 4 different brick walls getting cross-compiling going. I had wanted to get newer PulseAudio for the pi too (it's on v5, but the devs are working on v9)... I build a Jessie VM for compiling, installed all the stuff, and tried to get crosstool-ng running: let it spend about 35m running 4 cores on my laptop... crash. Etc.

I'm beginning to think that the rPi1 just isn't on the radar anymore; unfortunately, I have one running with an excellent DAC that I want to use :-)

**Comment by mfeif** [comment]
Hi there. I've had a chance to install your Jessie package on my rPi... I get "`Illegal instruction`" when trying to run it. Strangely, it DOES seem to be the right kind of file:

```
mjf@pifi:~ $ librespot --help
Illegal instruction
mjf@pifi:~ $ file /usr/bin/librespot 
/usr/bin/librespot: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=d4cce56d0e2a275cceb8dee4da2963fae50d7642, stripped
mjf@pifi:~ $ file /usr/bin/pulseaudio 
/usr/bin/pulseaudio: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=7b20a0b0ee259fb11fa28856cb8310e067a91d79, stripped
mjf@pifi:~ $ 
```

Is there anything else I can do to get more data about why it's not working?

I'll see if I can't get it compiling on my rpi1... I noticed in your dependency recommendations above that there is nothing about rust... do you have any advice for how to get this thing compiled into a .deb?

Thanks again for all your time.

**Comment by mfeif** [comment]
I'm unable to compile things now, seems that the rust compiler has a [bug](https://github.com/rust-lang/rust/issues/32377) that prevents it from compiling 'eventually'...

I can't figure out how to 'pin' a version of rust to use... seems like I can only choose stable, beta, nightly... :-(

Meanwhile, your .deb for x86_64 is wonderful, thank you!

**Comment by plietar** [comment]
I've changed librespot to use a pure rust mdns implementation, so it doesn't require linking to avahi anymore.
