### ISSUE TITLE
Is PulseAudio still supported?

### ISSUE THREAD

**Issue by bencevans** [plietar/librespot#83]
I'm getting the following on an x64 Ubuntu box...

```
/librespot/target/release/librespot --username $SPOTIFY_USERNAME --password=$SPOTIFY_PASSWORD --name bxps --appkey /etc/spotify_appkey.key --backend pulseaudio
INFO:librespot::main_helper: librespot 4d277e5 (2016-05-09). Built on 2016-05-14.
INFO:librespot::session: Connecting to AP lon2-accesspoint-a11.ap.spotify.com:80
INFO:librespot::session: Authenticated !
INFO:librespot::audio_backend::pulseaudio: Using PulseAudioSink
thread '<unnamed>' panicked at 'assertion failed: s != null_mut()', /librespot/target/release/build/librespot-2b132d5c5ccf58d4/out/lib.rs:836
stack backtrace:
   1:     0x55be0d18e3f0 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x55be0d190f0b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x55be0d190b78 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x55be0d17e52c - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x55be0cfe6bbf - sys_common::unwind::begin_unwind::h26420181488358413
   6:     0x55be0d00a04f - audio_backend::pulseaudio::PulseAudioSink.Open::open::h2cbc051af1d4ad49zqb
   7:     0x55be0d094e75 - audio_backend::mk_sink::h17800774558512200665
   8:     0x55be0d09830e - sys_common::unwind::try::try_fn::h9450263594518283024
   9:     0x55be0d18d7eb - __rust_try
  10:     0x55be0d18aa4d - sys_common::unwind::inner_try::hadd81c754a64f07ciYt
  11:     0x55be0d098a7c - boxed::F.FnBox<A>::call_box::h1742280503296891314
  12:     0x55be0d18fa89 - sys::thread::Thread::new::thread_start::h9bc812305b5e01feFPy
  13:     0x7fa2e02536f9 - start_thread
  14:     0x7fa2dff89b5c - clone
  15:                0x0 - <unknown>
DEBUG:librespot::spirc: kMessageTypeHello "bxps" c943c8a7b50126464b7d5ef27d7149ea69880dd8 1 1463202448294
DEBUG:librespot::spirc: kMessageTypeNotify "bxps" 35211575f7204be478a6bdb4cae34bac2d1e5473 20 1463202135098
DEBUG:librespot::spirc: kMessageTypeNotify "DESKTOP-1VQ1KU8" 905c2c89d5a3603f9785575b7914888e23b1b5bf 16 1463202135098
```

**Comment by lassos** [comment]
hi there, i also tried to install the source and got same error;

and i habe another question, if pulseaudio works, where can i setup the default output eg sink, gstreamer works like this:

--gstout-audiosink=pulsesink --gstout-audiodevice=Ch1mpd"

[CODE]
 RUST_BACKTRACE=1 target/release/librespot --appkey  /root//spotify-connect-web-chroot/usr/src/app/spotify_appkey.key --username larsmultihome --password schnuffi3 --bitrate 320 --name multihome --backend pulseaudio
INFO:librespot::main_helper: librespot 4d277e5 (2016-05-09). Built on 2016-05-15.
INFO:librespot::session: Connecting to AP lon3-accesspoint-a67.ap.spotify.com:443
INFO:librespot::session: Authenticated !
INFO:librespot::audio_backend::pulseaudio: Using PulseAudioSink
thread '<unnamed>' panicked at 'assertion failed: s != null_mut()', /steflaweb/librespot/target/release/build/librespot-c2d79cf4914625d2/out/lib.rs:836
stack backtrace:
   1: 0xb761f35c - sys::backtrace::tracing::imp::write::hcd9c6b761d959e16Xcv
   2: 0xb7621e71 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44492
   3: 0xb7621a6d - panicking::default_handler::hda9238d9f8e0ef0alSz
   4: 0xb760f939 - sys_common::unwind::begin_unwind_inner::h7224040aaffdbb98g1t
   5: 0xb74c9fc1 - sys_common::unwind::begin_unwind::h12088584803084974887
   6: 0xb74ecfe3 - audio_backend::pulseaudio::PulseAudioSink.Open::open::h4b8d1dba26e72188yqb
   7: 0xb7555375 - audio_backend::mk_sink::h33609298850789090
   8: 0xb7555335 - fn() .> Box<audio_backend..Sink $u2b$$u20$$u27$static$GT$$u20$$u7b$audio_backend..mk_sink$u7d$::fn_pointer_shim.29138::hb3057811a0531f02
   9: 0xb7558bfb - sys_common::unwind::try::try_fn::h6952317991051462395
  10: 0xb761e5e7 - __rust_try
  11: 0xb761ba46 - sys_common::unwind::inner_try::ha4db0d4f40d06c0fiYt
  12: 0xb7559319 - boxed::F.FnBox<A>::call_box::h8474876495701958265
  13: 0xb762098d - sys::thread::Thread::new::thread_start::h33eb81ff86657c76FPy
  14: 0xb739ec38 - <unknown>
DEBUG:librespot::spirc: kMessageTypeHello "multihome" b10091454a2d0bbe90a1de478aade751e9db9449 1 1463351609126
DEBUG:librespot::spirc: kMessageTypeNotify "SM-G900F" 63c6c288c88791a643e6cf68856e76bcba4fb468 2 1463350862658
DEBUG:librespot::spirc: kMessageTypeHello "SM-G900F" 63c6c288c88791a643e6cf68856e76bcba4fb468 148 1463350862658
DEBUG:librespot::spirc: kMessageTypeHello "SM-G900F" 63c6c288c88791a643e6cf68856e76bcba4fb468 147 1463350862658
DEBUG:librespot::spirc: kMessageTypeNotify "SM-G900F" 63c6c288c88791a643e6cf68856e76bcba4fb468 149 1463350862658
DEBUG:librespot::spirc: kMessageTypeNotify "multihome" b10091454a2d0bbe90a1de478aade751e9db9449 3 1463351609126
DEBUG:librespot::spirc: kMessageTypeNotify "multihome" b10091454a2d0bbe90a1de478aade751e9db9449 2 1463351609126
DEBUG:librespot::spirc: kMessageTypeHello "SM-G900F" 63c6c288c88791a643e6cf68856e76bcba4fb468 150 1463350862658
DEBUG:librespot::spirc: kMessageTypeHello "SM-G900F" 63c6c288c88791a643e6cf68856e76bcba4fb468 151 1463350862658
DEBUG:librespot::spirc: kMessageTypeNotify "multihome" b10091454a2d0bbe90a1de478aade751e9db9449 4 1463351609126
DEBUG:librespot::spirc: kMessageTypeNotify "multihome" b10091454a2d0bbe90a1de478aade751e9db9449 5 1463351609126
DEBUG:librespot::spirc: kMessageTypeLoad "SM-G900F" 63c6c288c88791a643e6cf68856e76bcba4fb468 3 0
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
stack backtrace:
   1: 0xb761f35c - sys::backtrace::tracing::imp::write::hcd9c6b761d959e16Xcv
   2: 0xb7621e71 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44492
   3: 0xb7621a6d - panicking::default_handler::hda9238d9f8e0ef0alSz
   4: 0xb760f939 - sys_common::unwind::begin_unwind_inner::h7224040aaffdbb98g1t
   5: 0xb760fe47 - sys_common::unwind::begin_unwind_fmt::h9d1eda8fc60b8ae3m0t
   6: 0xb761e6b1 - rust_begin_unwind
   7: 0xb76522f0 - panicking::panic_fmt::h559080aff49c30cclcM
   8: 0xb750c82b - result::unwrap_failed::h16661281073713254085
   9: 0xb750c58b - player::Player::command::h6b243aca38b2299eeQc
  10: 0xb754e6f5 - spirc::SpircManager::run::hc13f42580a30754axCd
  11: 0xb7479ed6 - sys_common::unwind::try::try_fn::h3606396648413695040
  12: 0xb761e5e7 - __rust_try
  13: 0xb761ba46 - sys_common::unwind::inner_try::ha4db0d4f40d06c0fiYt
  14: 0xb747a0f8 - boxed::F.FnBox<A>::call_box::h654272301819550317
  15: 0xb762098d - sys::thread::Thread::new::thread_start::h33eb81ff86657c76FPy
  16: 0xb739ec38 - <unknown>
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
stack backtrace:
   1: 0xb761f35c - sys::backtrace::tracing::imp::write::hcd9c6b761d959e16Xcv
   2: 0xb7621e71 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44492
   3: 0xb7621a6d - panicking::default_handler::hda9238d9f8e0ef0alSz
   4: 0xb760f939 - sys_common::unwind::begin_unwind_inner::h7224040aaffdbb98g1t
   5: 0xb760fe47 - sys_common::unwind::begin_unwind_fmt::h9d1eda8fc60b8ae3m0t
   6: 0xb761e6b1 - rust_begin_unwind
   7: 0xb76522f0 - panicking::panic_fmt::h559080aff49c30cclcM
   8: 0xb75055bf - result::unwrap_failed::h10220150407586851288
   9: 0xb7504be7 - mercury::MercuryManager::complete_request::hbd8d4c6ef1b30846djc
  10: 0xb7506c17 - mercury::MercuryManager.PacketHandler::handle::hbff4d367ebaa03d0omc
  11: 0xb7539e5c - session::Session::poll::h2624f49f8e187a16ssd
  12: 0xb7470d77 - main::h79a9c5601667de5bEba
  13: 0xb76216ea - sys_common::unwind::try::try_fn::h10144795978809605109
  14: 0xb761e5e7 - __rust_try
  15: 0xb76211a9 - rt::lang_start::he74f855a6a899d05rKz
  16: 0xb747a4ad - main
  17: 0xb7242e45 - <unknown>
[/CODE]

**Comment by lassos** [comment]
ok, got it working, i had to run as user mpd. an second. in defaul.pa i had to setup default sink instead of default sink null .-) 

very very nice, woooooooow, fantastic.

**Comment by marcust** [comment]
@bencevans I use it every day. There are some additions to the error handling that we could not get merged so far, because they need refactoring, on my fork https://github.com/marcust/librespot , can you try this and give the output?

Furthermore, have you tried to play over pulse with a different app?

**Comment by bencevans** [comment]
Think I was using it wrong, hadn't given permissions to access sound device. Got it working with portaudio :)
