### ISSUE TITLE
Does not work on Rust nightlies >=2015-08-12 

### ISSUE THREAD

**Issue by djmaze** [plietar/librespot#9]
On 2015-08-12 a major pile of [unstable deprecated functionality has been removed from Rust](https://github.com/rust-lang/rust/commit/8d90d3f36871a00023cc1f313f91e351c287ca15). That includes the [std::sync::Future](https://doc.rust-lang.org/std/sync/struct.Future.html) type which is used in librespot.

**Comment by plietar** [comment]
Thanks. Futures can easily be replaced by the eventual crate. However scoped threads have also been removed, and don't have any safe alternative, so the code using it needs to be redesigned quite a bit to use normal threads

**Comment by torarnv** [comment]
For now I downloaded an older rust nightly, but I'm guessing at some point we'll need a crate or a language feature that has been upgraded to use the latest nightly. @plietar do you foresee the thread redesign as something you'll work at?

**Comment by plietar** [comment]
Fixed by 267ccbe65edfdd0a780ed445737f2cfc46308aa8 on rustc 1.4.0-nightly (fe9cef7da 2015-08-30)
