### ISSUE TITLE
Binary size increased significantly

### ISSUE THREAD

**Issue by joerg-krause** [plietar/librespot#91]
The binary size between commit 4c04737a3dc9b0d4711a06baaa3d7ec25048ed35 and latest commit a9ae5b508633b1d1fc8906a7bf24a02d80abbc08 has almost doubled:

Commit 4c04737a3dc9b0d4711a06baaa3d7ec25048ed35

```
$ size target/release/librespot 
   text    data     bss     dec     hex filename
3021623  465185    6896 3493704  354f48 target/release/librespot
```

Commit a9ae5b508633b1d1fc8906a7bf24a02d80abbc08

```
$ size target/release/librespot 
   text    data     bss     dec     hex filename
5600351  541105    7792 6149248  5dd480 target/release/librespot
```

Build on x64 with rustc 1.10.0 and `cargo build --release`.

As I am using librespot on an ARMv5 board with limited size this makes me quite sad. For this target, the binary size increased significantly, too:

```
$ arm-linux-size target/armv5te-unknown-linux-musl/release/librespot 
   text    data     bss     dec     hex filename
2078982  264836     304 2344122  23c4ba target/armv5te-unknown-linux-musl/release/librespot

$ arm-linux-size target/armv5te-unknown-linux-musl/release/librespot 
   text    data     bss     dec     hex filename
4376367  306244    1632 4684243  4779d3 target/armv5te-unknown-linux-musl/release/librespot
```

**Comment by sashahilton00** [comment]
I haven't been following this project too closely of late, but could it be due to the fact that it now uses a pure rust version of mDNS?

**Comment by joerg-krause** [comment]
Not entirely. I recompiled librespot with commit b25585a41b7a3cf35776e20345e5718c3abf16b7 reverted:

```
$ size target/release/librespot 
   text    data     bss     dec     hex filename
5064479  519313    7760 5591552  555200 target/release/librespot
```

**Comment by plietar** [comment]
Adding serde was probably the cause (https://github.com/plietar/librespot/commit/24471eef9bbe7c96e828032b6bf09ed3bebf2551), as I think it's a fairly big dependency, and I can't see anything else in the log other than mDNS (https://github.com/plietar/librespot/compare/4c04737...master)

**Comment by joerg-krause** [comment]
Using LTO shrinks the binary size:

```
$ size target/release/librespot 
   text    data     bss     dec     hex filename
4256107  498825    5400 4760332  48a30c target/release/librespot
```

However, 4.7 MB is still quite heavy. Unfortunately, Cargo does not yet support to set the `opt-level` to `s`.

**Comment by plietar** [comment]
Got a bit of data wrt to dependency size here : https://gist.github.com/plietar/7dc48274c576ea4890910cf78d5a9f24
This is for an ARM release build, file is 8.4M in total.

```
$ arm-linux-gnueabihf-size target/arm-unknown-linux-gnueabihf/release/librespot
   text    data     bss     dec     hex filename
4726065  309449    4728 5040242  4ce872 target/arm-unknown-linux-gnueabihf/release/librespot
```

Using strip brings it down to 4.8M.

The biggest part in there is `librespot_protocol`, which is generated from the protobuf files, which accounts for 1.2M alone. I'll see if it can be reduced.

**Comment by joerg-krause** [comment]
Many thanks for looking into this issue and your detective work! The dependency script is a great tool for examining!

I tried some modifications on my ALSA repository to build librespot with a smaller size: https://github.com/joerg-krause/librespot/tree/compile:

```
$ arm-linux-size target/armv5te-unknown-linux-musl/release/librespot 
   text    data     bss     dec     hex filename
2683476  277512     848 2961836  2d31ac target/armv5te-unknown-linux-musl/release/librespot

$ readelf -d target/armv5te-unknown-linux-musl/release/librespot | grep NEEDED
 0x00000001 (NEEDED)                     Shared library: [libasound.so.2]
 0x00000001 (NEEDED)                     Shared library: [libdns_sd.so.1]
 0x00000001 (NEEDED)                     Shared library: [libvorbisidec.so.1]
 0x00000001 (NEEDED)                     Shared library: [libogg.so.0]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
 0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]
```

This is my gist for the dependencies: https://gist.github.com/joerg-krause/cbc4cd1236b35d7d5d0bcbae175a1bc6. Note, that liburl is listed twice with two different commits.

Unfortunately, Cargo does not allow to build with compiler options `s` or `z` to reduce the binary size.

**Comment by joerg-krause** [comment]
Using Cargos `-s` and LTO compiler options helps to reduce the binary size to ~2.1MB. This works for me. Therefore, I am closing this.

**Comment by cdlenfert** [comment]
@joerg-krause are you still able to compile and run librespot on armv5 devices? I'm having a hard time figuring out how to do it. Tried the cross compiler Docker image and the compiled arm-unknown-linux-gnueabi binary which runs perfectly fine on a non-floating-point armv6 device, but gets Illegal instruction output when trying it on armv5. If you could point me in the right direction I'd greatly appreciate it.

**Comment by joerg-krause** [comment]
@cdlenfert Sorry, I am not using librespot for quite some time. I've used https://github.com/joerg-krause/rust-cross-libs back than to compile it for ARMv5, but the project is not maintained anymore. Sorry. Maybe try xargo...

**Comment by cdlenfert** [comment]
@joerg-krause thanks for the response!
