### ISSUE TITLE
Support multiple mDNS backends

### ISSUE THREAD

**Issue by joerg-krause** [plietar/librespot#95]
It would be great if one can choose between the new internal and the previously supported Avahi mDNS backend.

The reason is that Avahi is widely spread in the Linux universe. Using the internal backend adds redundant functionality and furthermore increases the binary size which is undesirable for embedded targets.

**Comment by plietar** [comment]
I'd rather have an option to disable discovery than supporting different backends.
Multiple audio backends are already complicated enough.

By removing discovery altogether, you can also get rid of `hyper`, `url`, `idna`, `cookie`, and probably a few other small dependency. These account for quite a bit :
https://github.com/plietar/librespot/issues/91#issuecomment-233194833

librespot saves credentials (just a token, not the password) to disk, so even without discovery you only need to login once.

**Comment by joerg-krause** [comment]
I really like the discovery feature as it requires zero user configuration. This is my naive approach to support both backends: https://github.com/joerg-krause/librespot/commit/bd2ad97c068d4bad7dc52d1fd87d8f834393c289.

I know both features should be exclusive, but this is beyond my abilities for now.

**Comment by joerg-krause** [comment]
FWIW, I compared the binary sizes for building librespot with the internal and the avahi backend:

internal:

```
   text    data     bss     dec     hex filename
2638364  278916     860 2918140  2c86fc target/armv5te-unknown-linux-musl/release/librespot
```

avahi:

```
   text    data     bss     dec     hex filename
2497189  277504     852 2775545  2a59f9 target/armv5te-unknown-linux-musl/release/librespot
```

So, using the avahi-backend saves me around 140kB (avahi is already installed and needed by other processes).

I fully understand that you want to keep the build complexity low. However, as related to #91 it would be great to reduce the binary size especially for embedded devices.

**Comment by joerg-krause** [comment]
Eventually, I am fine using rust-mdns. So I close this...
